# Generated by Django 3.0.3 on 2020-02-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0007_auto_20200221_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=1, verbose_name='années')),
                ('number', models.IntegerField(verbose_name='numéro de lot')),
                ('quantity', models.IntegerField(verbose_name='quatité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify_number', models.CharField(max_length=10, unique=True, verbose_name="numéro d'identification")),
                ('product_model', models.CharField(choices=[('EDC15C2', 'EDC15C2'), ('EDC17', 'EDC17')], max_length=50, verbose_name='modèle produit')),
                ('product_reference', models.CharField(max_length=50, verbose_name='référence produit')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='numéro de série')),
                ('remark', models.CharField(blank=True, max_length=1000, verbose_name='remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quality_control', models.BooleanField(default=False, verbose_name='contrôle qualité')),
                ('checkout', models.BooleanField(default=False, verbose_name='contrôle de sortie')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='date de cloture')),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_number', to='reman.Batch')),
                ('batch_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_year', to='reman.Batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='commentaire')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reman.Repair')),
            ],
        ),
    ]
