# Generated by Django 3.0.8 on 2020-07-22 07:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=1, verbose_name='années')),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)], verbose_name='numéro de lot')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)], verbose_name='quantité')),
                ('batch_number', models.CharField(blank=True, max_length=10, unique=True, verbose_name='numéro de lot')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(null=True, verbose_name='date de début')),
                ('end_date', models.DateField(null=True, verbose_name='date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code defaut')),
                ('description', models.CharField(max_length=200, verbose_name='libellé')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify_number', models.CharField(max_length=10, unique=True, verbose_name="n° d'identification")),
                ('product_number', models.CharField(blank=True, max_length=50, verbose_name='référence')),
                ('remark', models.CharField(blank=True, max_length=1000, verbose_name='remarques')),
                ('quality_control', models.BooleanField(default=False, verbose_name='contrôle qualité')),
                ('checkout', models.BooleanField(default=False, verbose_name='contrôle de sortie')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='date de cloture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ajouté le')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='reman.Batch')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='repairs_created', to=settings.AUTH_USER_MODEL)),
                ('default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='reman.Default')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repairs_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_produit', models.CharField(max_length=100, verbose_name='code Produit')),
                ('code_magasin', models.CharField(blank=True, max_length=20, verbose_name='code Magasin')),
                ('code_zone', models.CharField(blank=True, max_length=20, verbose_name='code Zone')),
                ('code_site', models.IntegerField(blank=True, null=True, verbose_name='code Site')),
                ('code_emplacement', models.CharField(blank=True, max_length=10, verbose_name='code Emplacement')),
                ('cumul_dispo', models.IntegerField(blank=True, null=True, verbose_name='cumul Dispo')),
                ('repairs', models.ManyToManyField(blank=True, related_name='spare_part', to='reman.Repair')),
            ],
        ),
        migrations.CreateModel(
            name='EcuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_reference', models.CharField(max_length=10, unique=True, verbose_name='hardware')),
                ('technical_data', models.CharField(blank=True, max_length=50, verbose_name='modèle produit')),
                ('supplier_oe', models.CharField(blank=True, max_length=50, verbose_name='fabriquant')),
                ('spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reman.SparePart')),
            ],
        ),
        migrations.CreateModel(
            name='EcuRefBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reman_reference', models.CharField(max_length=10, unique=True, verbose_name='référence REMAN')),
                ('ecu_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reman.EcuType')),
            ],
        ),
        migrations.CreateModel(
            name='EcuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psa_barcode', models.CharField(max_length=10, unique=True, verbose_name='code barre PSA')),
                ('oe_raw_reference', models.CharField(max_length=10, verbose_name='réference OEM brute')),
                ('oe_reference', models.CharField(blank=True, max_length=10, verbose_name='référence OEM')),
                ('sw_reference', models.CharField(blank=True, max_length=10, verbose_name='software')),
                ('former_oe_reference', models.CharField(blank=True, max_length=50, verbose_name='ancienne référence OEM')),
                ('supplier_es', models.CharField(blank=True, max_length=50, verbose_name='service après vente')),
                ('ecu_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reman.EcuType')),
            ],
        ),
        migrations.AddField(
            model_name='default',
            name='ecu_type',
            field=models.ManyToManyField(blank=True, related_name='defaults', to='reman.EcuType'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='commentaire')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reman.Repair')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='ecu_ref_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reman.EcuRefBase'),
        ),
    ]
