# Generated by Django 3.0.3 on 2020-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateField(null=True, verbose_name='date de fin'),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_date',
            field=models.DateField(null=True, verbose_name='date de début'),
        ),
    ]
