# Generated by Django 3.0.7 on 2020-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecumodel',
            name='psa_barcode',
            field=models.CharField(max_length=10, unique=True, verbose_name='code barre PSA'),
        ),
        migrations.AlterField(
            model_name='ecutype',
            name='hw_reference',
            field=models.CharField(max_length=10, unique=True, verbose_name='hardware'),
        ),
    ]
