# Generated by Django 3.0.8 on 2020-07-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecumodel',
            name='oe_raw_reference',
            field=models.CharField(blank=True, max_length=10, verbose_name='réference OEM brute'),
        ),
        migrations.AlterField(
            model_name='ecurefbase',
            name='ecu_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecu_ref_base', to='reman.EcuType'),
        ),
    ]
