# Generated by Django 3.2.24 on 2024-04-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairCloseReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('extra', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Repair Close Reason',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='repair',
            name='closing_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='motif de clôture'),
        ),
    ]
