# Generated by Django 2.2.6 on 2019-11-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reman',
            name='product_model',
            field=models.CharField(choices=[('EDC15C2', 'EDC15C2'), ('EDC17', 'EDC17')], max_length=50, verbose_name='modèle produit'),
        ),
    ]
