# Generated by Django 3.1.1 on 2020-09-09 09:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0002_auto_20200729_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, verbose_name='Commentaires action'),
        ),
        migrations.AddField(
            model_name='repair',
            name='status',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Réparé', 'Réparé'), ('Rebut', 'Rebut')], default='En cours', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='remarques'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
