# Generated by Django 3.0.3 on 2020-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0002_auto_20200301_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_magasin', models.CharField(max_length=20, verbose_name='code Magasin')),
                ('code_produit', models.CharField(max_length=100, verbose_name='code Produit')),
                ('code_zone', models.CharField(max_length=20, verbose_name='code Zone')),
                ('code_site', models.IntegerField(verbose_name='code Site')),
                ('code_emplacement', models.CharField(max_length=10, verbose_name='code Emplacement')),
                ('cumul_dispo', models.IntegerField(verbose_name='cumul Dispo')),
                ('repairs', models.ManyToManyField(blank=True, related_name='spare_part', to='reman.Repair')),
            ],
        ),
    ]
