# Generated by Django 3.0.4 on 2020-04-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0002_remove_repair_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ajouté le'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
    ]
