# Generated by Django 3.0.4 on 2020-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0003_auto_20200403_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='numéro de lot'),
        ),
    ]
