# Generated by Django 3.1.1 on 2020-09-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0003_auto_20200909_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecumodel',
            options={'permissions': [('check_ecumodel', 'Check that the EcuModel instance exists')]},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'permissions': [('close_repair', 'Closing of the repair instance')]},
        ),
    ]
