# Generated by Django 3.0.4 on 2020-03-08 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reman', '0003_sparepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='repair',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repair',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repair',
            name='product_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='référence produit'),
        ),
    ]
