# Generated by Django 3.0.5 on 2020-04-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0004_batch_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='identify_number',
            field=models.CharField(max_length=10, unique=True, verbose_name="n° d'identification"),
        ),
    ]
