# Generated by Django 3.1.1 on 2020-09-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0004_auto_20200910_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecumodel',
            name='to_dump',
            field=models.BooleanField(default=False, verbose_name='à dumper'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='code_emplacement',
            field=models.CharField(blank=True, max_length=50, verbose_name='code Emplacement'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='code_magasin',
            field=models.CharField(blank=True, max_length=50, verbose_name='code Magasin'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='code_zone',
            field=models.CharField(blank=True, max_length=50, verbose_name='code Zone'),
        ),
    ]
