# Generated by Django 3.0.5 on 2020-04-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0005_auto_20200410_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code defaut')),
                ('description', models.CharField(max_length=200, verbose_name='libellé')),
            ],
        ),
        migrations.AddField(
            model_name='repair',
            name='Breakdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='reman.Breakdown'),
        ),
    ]
