# Generated by Django 3.0.5 on 2020-05-27 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0006_auto_20200414_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecumodel',
            name='es_raw_reference',
            field=models.CharField(max_length=10, verbose_name='référence EMS brute'),
        ),
        migrations.AlterField(
            model_name='ecumodel',
            name='es_reference',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='référence EMS'),
        ),
        migrations.CreateModel(
            name='EcuRefBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psa_barcode', models.CharField(blank=True, max_length=10, verbose_name='code barre PSA')),
                ('ecu_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reman.EcuModel')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reman.SparePart')),
            ],
        ),
    ]
