# Generated by Django 3.1.7 on 2021-03-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0008_auto_20201118_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecumodel',
            name='psa_barcode',
            field=models.CharField(max_length=20, unique=True, verbose_name='code barre PSA'),
        ),
        migrations.AlterField(
            model_name='ecutype',
            name='hw_reference',
            field=models.CharField(max_length=20, unique=True, verbose_name='hardware'),
        ),
    ]
