# Generated by Django 3.2 on 2021-05-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0009_auto_20210329_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecurefbase',
            name='cal_ktag',
        ),
        migrations.RemoveField(
            model_name='ecurefbase',
            name='open_diag',
        ),
        migrations.RemoveField(
            model_name='ecurefbase',
            name='ref_cal_out',
        ),
        migrations.RemoveField(
            model_name='ecurefbase',
            name='ref_comp',
        ),
        migrations.RemoveField(
            model_name='ecurefbase',
            name='ref_mat',
        ),
        migrations.RemoveField(
            model_name='ecurefbase',
            name='ref_psa_out',
        ),
        migrations.RemoveField(
            model_name='ecurefbase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='repairs',
        ),
        migrations.AddField(
            model_name='ecutype',
            name='cal_ktag',
            field=models.CharField(blank=True, max_length=10, verbose_name='CAL_KTAG'),
        ),
        migrations.AddField(
            model_name='ecutype',
            name='open_diag',
            field=models.CharField(blank=True, max_length=16, verbose_name='OPENDIAG'),
        ),
        migrations.AddField(
            model_name='ecutype',
            name='ref_cal_out',
            field=models.CharField(blank=True, max_length=10, verbose_name='REF_CAL_OUT'),
        ),
        migrations.AddField(
            model_name='ecutype',
            name='ref_comp',
            field=models.CharField(blank=True, max_length=10, verbose_name='REF_COMP'),
        ),
        migrations.AddField(
            model_name='ecutype',
            name='ref_mat',
            field=models.CharField(blank=True, max_length=10, verbose_name='REF_MAT'),
        ),
        migrations.AddField(
            model_name='ecutype',
            name='ref_psa_out',
            field=models.CharField(blank=True, max_length=10, verbose_name='REF_PSA_OUT'),
        ),
        migrations.AddField(
            model_name='ecutype',
            name='status',
            field=models.CharField(blank=True, max_length=16, verbose_name='STATUT'),
        ),
        migrations.AlterField(
            model_name='ecutype',
            name='hw_reference',
            field=models.CharField(max_length=20, verbose_name='hardware'),
        ),
        migrations.AlterField(
            model_name='ecutype',
            name='technical_data',
            field=models.CharField(max_length=50, verbose_name='modèle produit'),
        ),
        migrations.AlterUniqueTogether(
            name='ecutype',
            unique_together={('hw_reference', 'technical_data')},
        ),
    ]
