# Generated by Django 3.2 on 2021-05-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0010_auto_20210504_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecutype',
            name='cle_appli',
            field=models.CharField(blank=True, max_length=50, verbose_name='CLE_APPLI'),
        ),
        migrations.AddField(
            model_name='ecutype',
            name='req_cal',
            field=models.CharField(blank=True, max_length=50, verbose_name='REQ_CAL'),
        ),
        migrations.AddField(
            model_name='ecutype',
            name='req_diag',
            field=models.CharField(blank=True, max_length=50, verbose_name='REQ_DIAG'),
        ),
        migrations.AddField(
            model_name='ecutype',
            name='req_ref',
            field=models.CharField(blank=True, max_length=50, verbose_name='REQ_REF'),
        ),
        migrations.AddField(
            model_name='ecutype',
            name='req_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='REQ_STATUS'),
        ),
        migrations.AddField(
            model_name='ecutype',
            name='test_clear_memory',
            field=models.CharField(blank=True, max_length=10, verbose_name='TEST_CLEAR_MEMORY'),
        ),
        migrations.AlterField(
            model_name='ecurefbase',
            name='ecu_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecu_ref_base', to='reman.ecutype'),
        ),
        migrations.AlterField(
            model_name='ecutype',
            name='open_diag',
            field=models.CharField(blank=True, max_length=50, verbose_name='OPENDIAG'),
        ),
        migrations.AlterField(
            model_name='ecutype',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='STATUT'),
        ),
    ]
