# Generated by Django 3.2.3 on 2021-05-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0011_auto_20210511_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecumodel',
            options={'permissions': [('check_ecumodel', 'Can check ecu model')]},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'permissions': [('close_repair', 'Can close repair')]},
        ),
    ]
