# Generated by Django 3.2.3 on 2021-05-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0013_alter_ecutype_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecutype',
            name='hw_reference',
            field=models.CharField(max_length=20, unique=True, verbose_name='hardware'),
        ),
    ]
