# Generated by Django 3.2.4 on 2021-06-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0015_alter_repair_psa_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecutype',
            name='cal_ktag',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='cle_appli',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='open_diag',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='ref_cal_out',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='ref_comp',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='ref_mat',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='ref_psa_out',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='req_cal',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='req_diag',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='req_ref',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='req_status',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ecutype',
            name='test_clear_memory',
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='cal_ktag',
            field=models.CharField(blank=True, max_length=10, verbose_name='CAL_KTAG'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='cle_appli',
            field=models.CharField(blank=True, max_length=50, verbose_name='CLE_APPLI'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='open_diag',
            field=models.CharField(blank=True, max_length=50, verbose_name='OPENDIAG'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='ref_cal_out',
            field=models.CharField(blank=True, max_length=10, verbose_name='REF_CAL_OUT'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='ref_comp',
            field=models.CharField(blank=True, max_length=10, verbose_name='REF_COMP'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='ref_mat',
            field=models.CharField(blank=True, max_length=10, verbose_name='REF_MAT'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='ref_psa_out',
            field=models.CharField(blank=True, max_length=10, verbose_name='REF_PSA_OUT'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='req_cal',
            field=models.CharField(blank=True, max_length=50, verbose_name='REQ_CAL'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='req_diag',
            field=models.CharField(blank=True, max_length=50, verbose_name='REQ_DIAG'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='req_ref',
            field=models.CharField(blank=True, max_length=50, verbose_name='REQ_REF'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='req_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='REQ_STATUS'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='STATUT'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='test_clear_memory',
            field=models.CharField(blank=True, max_length=10, verbose_name='TEST_CLEAR_MEMORY'),
        ),
        migrations.AlterField(
            model_name='ecurefbase',
            name='ecu_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reman.ecutype'),
        ),
    ]
