# Generated by Django 3.2.4 on 2021-07-08 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0017_alter_batch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='box_quantity',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='quantité du carton'),
        ),
    ]
