# Generated by Django 3.2.11 on 2022-01-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0020_auto_20220106_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repair',
            old_name='psa_barcode',
            new_name='barcode',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='brand',
        ),
        migrations.AddField(
            model_name='batch',
            name='customer',
            field=models.CharField(default='PSA', max_length=50, verbose_name='client'),
        ),
        migrations.AddField(
            model_name='repair',
            name='new_barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='nouveau code barre'),
        ),
    ]
