# Generated by Django 3.2.11 on 2022-01-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0021_auto_20220117_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repair',
            options={'permissions': [('close_repair', 'Can close repair'), ('stock_repair', 'Can stock repair')]},
        ),
        migrations.AddField(
            model_name='batch',
            name='is_barcode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repair',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='code barre'),
        ),
    ]
