# Generated by Django 3.2.11 on 2022-01-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0022_auto_20220117_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecumodel',
            old_name='psa_barcode',
            new_name='barcode',
        ),
    ]
