# Generated by Django 3.2.11 on 2022-01-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0023_rename_psa_barcode_ecumodel_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecumodel',
            name='supplier_es',
        ),
        migrations.RemoveField(
            model_name='ecumodel',
            name='sw_reference',
        ),
        migrations.AddField(
            model_name='ecumodel',
            name='fan',
            field=models.CharField(blank=True, max_length=100, verbose_name='FAN'),
        ),
        migrations.AddField(
            model_name='ecumodel',
            name='rear_bolt',
            field=models.CharField(blank=True, max_length=100, verbose_name='REAR BOLT'),
        ),
        migrations.AddField(
            model_name='ecumodel',
            name='vehicle',
            field=models.CharField(blank=True, max_length=50, verbose_name='vehicule'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='map_data',
            field=models.CharField(blank=True, max_length=100, verbose_name='map data'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='pf_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='PF code REMAN'),
        ),
        migrations.AddField(
            model_name='ecurefbase',
            name='product_part',
            field=models.CharField(blank=True, max_length=8, verbose_name='product part'),
        ),
        migrations.AlterField(
            model_name='ecumodel',
            name='barcode',
            field=models.CharField(max_length=50, unique=True, verbose_name='code barre PSA'),
        ),
        migrations.AlterField(
            model_name='ecumodel',
            name='oe_raw_reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='référence OEM brute'),
        ),
        migrations.AlterField(
            model_name='ecumodel',
            name='oe_reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='référence OEM'),
        ),
    ]
