# Generated by Django 3.2.11 on 2022-01-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reman', '0024_auto_20220125_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='sem_ref_base',
        ),
        migrations.AddField(
            model_name='batch',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de cloture'),
        ),
        migrations.CreateModel(
            name='RepairPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, verbose_name='code produit')),
                ('part_number', models.CharField(max_length=100, verbose_name='n° de pièce')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Pièce réparation',
            },
        ),
    ]
