# Generated by Django 3.2.11 on 2022-01-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0025_auto_20220125_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repair',
            options={'ordering': ['-modified_at'], 'permissions': [('close_repair', 'Can close repair'), ('stock_repair', 'Can stock repair')]},
        ),
        migrations.AddField(
            model_name='ecutype',
            name='hw_type',
            field=models.CharField(choices=[('ECU', 'ECU'), ('NAV', 'NAV')], default='ECU', max_length=50, verbose_name='type HW'),
        ),
        migrations.AddField(
            model_name='repair',
            name='face_plate',
            field=models.BooleanField(default=False, verbose_name='façade'),
        ),
        migrations.AddField(
            model_name='repair',
            name='fan',
            field=models.BooleanField(default=False, verbose_name='ventilateur'),
        ),
        migrations.AddField(
            model_name='repair',
            name='locating_pin',
            field=models.BooleanField(default=False, verbose_name="goupille d'emplacement"),
        ),
        migrations.AddField(
            model_name='repair',
            name='metal_case',
            field=models.BooleanField(default=False, verbose_name='boitier'),
        ),
        migrations.AddField(
            model_name='repair',
            name='spring_locking',
            field=models.BooleanField(default=False, verbose_name='verrouillage à ressort'),
        ),
        migrations.AlterField(
            model_name='ecutype',
            name='hw_reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='hardware'),
        ),
    ]
