# Generated by Django 3.2.12 on 2022-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0027_alter_repairpart_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repairpart',
            old_name='part_number',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='repair',
            name='locating_pin',
            field=models.BooleanField(default=False, verbose_name='Boulon arrière'),
        ),
    ]
