# Generated by Django 3.2.12 on 2022-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0029_repair_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='code defaut'),
        ),
    ]
