# Generated by Django 3.2.15 on 2022-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman', '0031_repair_diagnostic_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='active',
            field=models.BooleanField(default=True, verbose_name='terminé'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='is_barcode',
            field=models.BooleanField(default=False, verbose_name='Nouveau code barre'),
        ),
    ]
