# Generated by Django 2.2.1 on 2019-05-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raspeedi',
            fields=[
                ('ref_boitier', models.BigIntegerField(primary_key=True, serialize=False)),
                ('produit', models.CharField(max_length=20)),
                ('facade', models.CharField(max_length=2)),
                ('type', models.CharField(max_length=3)),
                ('dab', models.BooleanField(default=False)),
                ('cam', models.BooleanField(default=False)),
                ('dump_peedi', models.CharField(max_length=25, null=True)),
                ('cd_version', models.CharField(max_length=10, null=True)),
                ('media', models.CharField(max_length=20, null=True)),
                ('carto', models.CharField(max_length=20, null=True)),
                ('dump_renesas', models.CharField(max_length=50, null=True)),
                ('ref_mm', models.CharField(max_length=200, null=True)),
                ('connecteur_ecran', models.IntegerField(null=True)),
            ],
        ),
    ]
