# Generated by Django 2.2.1 on 2019-06-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raspeedi',
            fields=[
                ('ref_boitier', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='référence boîtier')),
                ('produit', models.CharField(choices=[('RT4', 'RT4'), ('RT5', 'RT5'), ('RT6', 'RT6'), ('RT6v2', 'RT6 version 2'), ('SMEG', 'SMEG'), ('SMEGP', 'SMEG+ / SMEG+ IV1'), ('SMEGP2', 'SMEG+ IV2')], max_length=20)),
                ('facade', models.CharField(max_length=2, verbose_name='façade')),
                ('type', models.CharField(choices=[('RAD', 'Radio'), ('NAV', 'Navigation')], max_length=3)),
                ('dab', models.BooleanField(default=False, verbose_name='DAB')),
                ('cam', models.BooleanField(default=False, verbose_name='caméra de recul')),
                ('dump_peedi', models.CharField(blank=True, max_length=25, null=True, verbose_name='dump PEEDI')),
                ('cd_version', models.CharField(blank=True, max_length=10, null=True)),
                ('media', models.CharField(choices=[('N/A', 'Vide'), ('HDD', 'Disque Dur'), ('8Go', 'Carte SD 8Go'), ('16Go', 'Carte SD 16Go'), ('8Go 16Go', 'Carte SD 8 ou 16 Go')], max_length=20, null=True, verbose_name='type de média')),
                ('carto', models.CharField(blank=True, max_length=20, null=True, verbose_name='version cartographie')),
                ('dump_renesas', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_mm', models.CharField(blank=True, max_length=200, null=True)),
                ('connecteur_ecran', models.IntegerField(choices=[(1, '1'), (2, '2')], null=True, verbose_name="nombre de connecteur d'écran")),
            ],
        ),
    ]
