# Generated by Django 2.2.1 on 2019-05-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raspeedi',
            fields=[
                ('ref_boitier', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='référence boîtier')),
                ('produit', models.CharField(max_length=20)),
                ('facade', models.CharField(max_length=2, verbose_name='façade')),
                ('type', models.CharField(max_length=3)),
                ('dab', models.BooleanField(default=False, verbose_name='DAB')),
                ('cam', models.BooleanField(default=False, verbose_name='caméra de recul')),
                ('dump_peedi', models.CharField(max_length=25, null=True, verbose_name='dump PEEDI')),
                ('cd_version', models.CharField(max_length=10, null=True)),
                ('media', models.CharField(max_length=20, null=True, verbose_name='type de média')),
                ('carto', models.CharField(max_length=20, null=True, verbose_name='version cartographie')),
                ('dump_renesas', models.CharField(max_length=50, null=True)),
                ('ref_mm', models.CharField(max_length=200, null=True)),
                ('connecteur_ecran', models.IntegerField(null=True, verbose_name="nombre de connecteur d'écran")),
            ],
        ),
    ]
