# Generated by Django 2.2.1 on 2019-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspeedi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspeedi',
            name='cam',
            field=models.BooleanField(default=False, verbose_name='caméra de recul'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='carto',
            field=models.CharField(max_length=20, null=True, verbose_name='version cartographie'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='connecteur_ecran',
            field=models.IntegerField(null=True, verbose_name="nombre de connecteur d'écran"),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='dab',
            field=models.BooleanField(default=False, verbose_name='DAB'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='dump_peedi',
            field=models.CharField(max_length=25, null=True, verbose_name='dump PEEDI'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='facade',
            field=models.CharField(max_length=2, verbose_name='façade'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='media',
            field=models.CharField(max_length=20, null=True, verbose_name='type de média'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='ref_boitier',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='référence boîtier'),
        ),
    ]
