# Generated by Django 2.2.2 on 2019-06-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_csdsoftware'),
        ('raspeedi', '0002_raspeedi_corvets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('add_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspeedi.Raspeedi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserProfile')),
            ],
        ),
    ]
