# Generated by Django 2.2.5 on 2019-09-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190709_0957'),
        ('squalaetp', '0012_auto_20190829_1605'),
        ('raspeedi', '0005_auto_20190704_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserProfile'),
        ),
        migrations.CreateModel(
            name='UnlockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squalaetp.Xelon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserProfile')),
            ],
        ),
    ]
