# Generated by Django 2.2.5 on 2019-10-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raspeedi', '0007_auto_20190916_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raspeedi',
            options={'ordering': ['ref_boitier'], 'verbose_name': 'Données RASPEEDI'},
        ),
    ]
