# Generated by Django 3.0.4 on 2020-03-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspeedi', '0008_auto_20191004_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspeedi',
            name='cd_version',
            field=models.CharField(blank=True, max_length=10, verbose_name='version CD'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='dump_renesas',
            field=models.CharField(blank=True, max_length=50, verbose_name='dump RENESAS'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='produit',
            field=models.CharField(choices=[('RT4', 'RT4'), ('RT5', 'RT5'), ('RT6', 'RT6'), ('RT6v2', 'RT6 version 2'), ('SMEG', 'SMEG'), ('SMEGP', 'SMEG+ / SMEG+ IV1'), ('SMEGP2', 'SMEG+ IV2')], max_length=20, verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='ref_mm',
            field=models.CharField(blank=True, max_length=200, verbose_name='référence MM'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='type',
            field=models.CharField(choices=[('RAD', 'Radio'), ('NAV', 'Navigation')], max_length=3, verbose_name='type'),
        ),
    ]
