# Generated by Django 3.1.2 on 2020-11-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raspeedi', '0010_auto_20200403_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unlockproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Déverrouillage VIN'},
        ),
    ]
