# Generated by Django 3.1.2 on 2020-11-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0006_auto_20201122_1453'),
        ('raspeedi', '0012_programing'),
    ]

    operations = [
        migrations.AddField(
            model_name='programing',
            name='multimedia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psa.multimedia'),
        ),
    ]
