# Generated by Django 3.1.3 on 2020-12-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raspeedi', '0013_programing_multimedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspeedi',
            name='corvets',
        ),
    ]
