"""
Django settings for sbadmin project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import shutil
from pathlib import Path
from collections import OrderedDict

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'q2sb*vqltbpi59f#l2c&mak*%h&xzv1)i^#e0_as^cmx^-9)8x'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
#
# ALLOWED_HOSTS = []

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    # django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'ckeditor',
    'tempus_dominus',
    'bootstrap_modal_forms',
    'widget_tweaks',
    'constance',
    'django_inlinecss',
    'celery_progress',
    'django_celery_beat',
    'django_celery_results',
    'encrypted_fields',
    'channels',

    # Django-wiki
    'django.contrib.sites.apps.SitesConfig',
    'django.contrib.humanize.apps.HumanizeConfig',
    'django_nyt.apps.DjangoNytConfig',
    'mptt',
    'sekizai',
    'sorl.thumbnail',
    'wiki.apps.WikiConfig',
    'wiki.plugins.attachments.apps.AttachmentsConfig',
    'wiki.plugins.notifications.apps.NotificationsConfig',
    'wiki.plugins.images.apps.ImagesConfig',
    'wiki.plugins.macros.apps.MacrosConfig',

    # My apps
    'dashboard.apps.DashboardConfig',
    'prog.apps.RaspeediConfig',
    'squalaetp.apps.SqualaetpConfig',
    'reman.apps.RemanConfig',
    'tools.apps.ToolsConfig',
    'api.apps.ApiConfig',
    'import_export.apps.ImportExportConfig',
    'psa.apps.PsaConfig',
    'ford.apps.FordConfig',
    'renault.apps.RenaultConfig',
    'vag.apps.VagConfig',
    'volvo.apps.VolvoConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',
]

ROOT_URLCONF = 'sbadmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                "sekizai.context_processors.sekizai",
                'sbadmin.context_processors.global_infos',
                'sbadmin.context_processors.global_emails',
                'sbadmin.context_processors.global_forms',
            ],
        },
    },
]

# WSGI_APPLICATION = 'sbadmin.wsgi.application'
ASGI_APPLICATION = 'sbadmin.routing.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# API REST Framework
# https://www.django-rest-framework.org

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'api.utils.TokenAuthSupportQueryString',
    ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DATETIME_FORMAT': '%d-%m-%Y %H:%M:%S',
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'fr'
TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True

gettext = lambda x: x

LANGUAGES = (
    ('fr', gettext('French')),
    ('en', gettext('English')),
)

# LOCALE_PATHS = [x / 'locale' for x in BASE_DIR.iterdir() if x.is_dir()]
LOCALE_PATHS = [
    os.path.join(Path(__file__).resolve().parent.parent, 'locale'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = '/dashboard/charts/'
LOGOUT_REDIRECT_URL = '/'

# Configuration sessions
# https://docs.djangoproject.com/en/3.2/ref/settings/#sessions

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 1209600

# Django Logging configuration
# https://docs.djangoproject.com/en/3.2/topics/logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] [{process:d}] [{levelname}] {message}',
            'datefmt': "%Y-%m-%d %H:%M:%S",
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'console_verbose': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'mail_admin': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console_verbose'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'WARNING'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['mail_admin'],
            'level': 'ERROR',
            'propagate': False,
        },
        'command': {
            'handlers': ['mail_admin', 'console_verbose'],
            'level': 'ERROR',
            'propagate': False,
        },
        'celery': {
            'handlers': ['mail_admin', 'console_verbose'],
            'level': 'ERROR',
            'propagate': False,
        }
    },
}

#######################
# CUSTOM CONFIGURATION
#######################

# Configuration CkEditor
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'width': 765,
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', '-', 'CopyFormatting', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter',
             'JustifyRight', 'JustifyBlock'],
            ['TextColor', 'BGColor', '-', 'Link', 'Unlink', 'Anchor'],
            ['Scayt', '-', 'Source']
        ],
    },
    'comment': {
        'toolbar': 'Custom',
        'height': 200,
        'width': '100%',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', '-', 'CopyFormatting', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter',
             'JustifyRight', 'JustifyBlock'],
            ['TextColor', 'BGColor', 'FontSize', '-', 'Link', 'Unlink', 'Anchor'],
            ['Scayt', '-', 'Source']
        ],
    }
}

# Configuration Tempus Dominus
TEMPUS_DOMINUS_LOCALIZE = True
TEMPUS_DOMINUS_INCLUDE_ASSETS = False

# Configuration DJANGO-CONSTANCE
CONSTANCE_BACKEND = 'constance.backends.redisd.RedisBackend'
CONSTANCE_REDIS_CONNECTION = 'redis://localhost:6379/1'

CONSTANCE_ADDITIONAL_FIELDS = {
    'yes_no_field': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': ((True, "Yes"), (False, "No"))
    }],
    'pwd_field': ['django.forms.fields.CharField', {
        'widget': 'django.forms.PasswordInput',
        'widget_kwargs': {'render_value': True},
        'required': False
    }],
}

CONSTANCE_CONFIG = OrderedDict({
    # General Options
    'SITE_NAME': ('CSD Dashboard', 'Website title'),
    'SITE_DESCRIPTION': ('', 'Website description'),
    'WEBSITE_DOMAIN': ('127.0.0.1:8000', 'Webside domain name'),
    'WIKI_URL': ('127.0.0.1:8001', 'URL of the wiki web application'),
    'SYS_REPORT_TO_MAIL_LIST': ('system1@test.com; system2@test.com', 'System report TO email list'),
    'CONTRACT_TO_EMAIL_LIST': ('contract1@test.com; contract2@test.com', 'Contracts TO email list'),

    # Network Options
    'BASE_DIR': ('~/Documents/CSD_DATABASE', 'Network drive path'),
    'NAS_DIR': ('', 'Network NAS drive path'),
    'XLS_RASPEEDI_FILE': ('PROG/RASPEEDI/table_boitier_PSA.xlsx', 'xls raspeedi file'),
    'XLS_SQUALAETP_FILE': ('EXTS/squalaetp.xls', 'xls squalaetp file'),
    'XLS_ATTRIBUTS_FILE': ('EXTS/Attributs CORVET.xlsx', 'xls attributs file'),
    'CSV_EXTRACTION_FILE': ('EXTS/extraction.csv', 'csv extraction file'),
    'XLS_DELAY_PATH': ('RH/AnalyseRetards', 'Path of xls delay files'),
    'XLS_DELAY_FILES': (
        'PSA.xlsx, ILOTAUTRE.xlsx, LaboQual.xlsx, DEFAUT.xlsx, CLARION.xlsx', 'List of xls delay file'
    ),
    'XLS_TIME_LIMIT_FILE': ('RH/Analyse_Delais/data/DELAIS_REP_A.xls', 'xls time limit file'),
    'XML_CORVET_PATH': ('LOGS/CORVET_XML_TEST', 'xml Corvet path'),
    'TAG_XELON_PATH': ('LOGS/CALIBRE', 'tag xelon path'),
    'TAG_XELON_LOG_PATH': ('LOGS/LOG_CONFIG_PROD', 'tag xelon log path'),
    'TAG_XELON_TEL_PATH': ('LOGS/TELECODAGE', 'tag xelon télécodage path'),

    # CSD Repair Options
    'VIN_ERROR_TO_EMAIL_LIST': ('test1@test.com; test2@test.com', 'VIN error TO email list'),
    'LATE_PRODUCTS_TO_EMAIL_LIST': ('test1@test.com; test2@test.com', 'Late products TO email list'),
    'PENDING_PRODUCTS_TO_EMAIL_LIST': ('test1@test.com; test2@test.com', 'Pending products TO email list'),
    'REMAN_TO_EMAIL_LIST': ('test1@test.com; test2@test.com', 'REMAN TO email list'),
    'CHANGE_VIN_TO_EMAIL_LIST': ('test1@test.com; test2@test.com', 'Change Xelon VIN TO email list'),
    'CHANGE_PROD_TO_EMAIL_LIST': ('test1@test.com; test2@test.com', 'Change Xelon produit TO email list'),
    'CSD_CC_EMAIL_LIST': ('test1@test.com; test2@test.com', 'CSD Atelier CC email list'),
    'SQUALAETP_FILE_LIST': ('squalaetp_cal.xls, squalaetp_ecu.xls, squalaetp_prog.xls', 'Squalaetp file list'),

    # REMAN Options
    'ECU_TO_EMAIL_LIST': ('test1@test.com; test2@test.com', 'REMAN TO email list'),
    'ECU_CC_EMAIL_LIST': ('', 'REMAN CC email list'),
    'BATCH_EXPORT_FILE': ('EXTS/reman_lots.csv', 'File name for exporting batch'),
    'REPAIR_EXPORT_FILE': ('EXTS/reman_repairs.csv', 'File name for exporting repairs'),
    'CHECKOUT_EXPORT_FILE': ('EXTS/reman_output.csv', 'File name for exporting data from check out'),
    'SCAN_IN_OUT_EXPORT_FILE': ('EXTS/BASE_REF_REMAN.xlsx', 'File name for exporting Base Ref REMAN of SCAN IN/OUT'),
    'DICT_YEAR': (
        "{2020: 'C', 2021: 'D', 2022: 'G', 2023: 'H', 2024: 'K', 2025: 'L', 2026: 'O', 2027: 'T', 2028: 'U'}",
        'REMAN batch date formatting dictionary'
    ),
    'CHECKOUT_BATCH_FILTER_DISABLE': (False, 'Checkout batch filter deactivation', 'yes_no_field'),

    # MQTT Options
    "MQTT_TOPIC": ('TEMP/TC-01', 'Topic subcribe'),
    'MQTT_TEMP_ADJ': (4, 'Temp adjust', int),
    'MQTT_CLIENT': ('', 'Client name'),
    'MQTT_USER': ('', 'Login'),
    'MQTT_PSWD': ('', 'Password', 'pwd_field'),
    'MQTT_BROKER': ('test.mosquitto.org', 'Server address'),
    'MQTT_PORT': (1883, 'Server port', int),
    'KEEP_ALIVE': (45, 'Keep alive', int),

    # tools Options
    'SUPTECH_TO_EMAIL_LIST': ('test1@test.com; test2@test.com', 'Suptech TO email list'),
    'SUPTECH_CC_EMAIL_LIST': ('test1@test.com; test2@test.com', 'Suptech Manager TO email list'),
    'PRINTER_STREAM_URL': ('http://10.115.141.42:8080/?action=stream', '3D printer streaming URL'),
    'PROXY_HOST_SCRAPING': ('', 'Proxy HOST for Scraping'),
    'PROXY_PORT_SCRAPING': ('', 'Proxy PORT for Scraping'),
    'CORVET_USER': ('', 'CORVET user for RepairLab'),
    'CORVET_PWD': ('', 'CORVET password for RepairLab', 'pwd_field'),
    'PL24_ACCOUNT': ('', 'Account for PartsLink24'),
    'PL24_USER': ('', 'User for PartsLink24'),
    'PL24_PWD': ('', 'Password for PartsLink24', 'pwd_field')
})

CONSTANCE_CONFIG_FIELDSETS = {
    '1. General Options': {
        'fields': ('SITE_NAME', 'SITE_DESCRIPTION', 'WEBSITE_DOMAIN', 'WIKI_URL', 'SYS_REPORT_TO_MAIL_LIST',
                   'CONTRACT_TO_EMAIL_LIST'),
        'collapse': True
    },
    '2. Network Options': {
        'fields': ('BASE_DIR', 'NAS_DIR', 'XLS_RASPEEDI_FILE', 'XLS_SQUALAETP_FILE', 'XLS_ATTRIBUTS_FILE',
                   'CSV_EXTRACTION_FILE', 'XLS_DELAY_PATH', 'XLS_DELAY_FILES', 'XLS_TIME_LIMIT_FILE', 'XML_CORVET_PATH',
                   'TAG_XELON_PATH', 'TAG_XELON_LOG_PATH', 'TAG_XELON_TEL_PATH'),
        'collapse': False
    },
    '3. CSD Repair Options': {
        'fields': ('VIN_ERROR_TO_EMAIL_LIST', 'LATE_PRODUCTS_TO_EMAIL_LIST', 'PENDING_PRODUCTS_TO_EMAIL_LIST',
                   'REMAN_TO_EMAIL_LIST', 'CHANGE_VIN_TO_EMAIL_LIST', 'CHANGE_PROD_TO_EMAIL_LIST', 'CSD_CC_EMAIL_LIST',
                   'SQUALAETP_FILE_LIST'),
        'collapse': False
    },
    '4. REMAN Options': {
        'fields': ('ECU_TO_EMAIL_LIST', 'ECU_CC_EMAIL_LIST', 'BATCH_EXPORT_FILE', 'REPAIR_EXPORT_FILE',
                   'CHECKOUT_EXPORT_FILE', 'SCAN_IN_OUT_EXPORT_FILE', 'DICT_YEAR', 'CHECKOUT_BATCH_FILTER_DISABLE'),
        'collapse': False
    },
    '5. Tools Options': {
        'fields': ('SUPTECH_TO_EMAIL_LIST', 'SUPTECH_CC_EMAIL_LIST', 'PRINTER_STREAM_URL', 'PROXY_HOST_SCRAPING',
                   'PROXY_PORT_SCRAPING', 'CORVET_USER', 'CORVET_PWD', 'PL24_ACCOUNT', 'PL24_USER', 'PL24_PWD'),
        'collapse': False
    },
    '6. MQTT Options': {
        'fields': ('MQTT_TOPIC', 'MQTT_TEMP_ADJ', 'MQTT_CLIENT', 'MQTT_USER', 'MQTT_PSWD', 'MQTT_BROKER', 'MQTT_PORT',
                   'KEEP_ALIVE'),
        'collapse': True
    },
}

# CELERY STUFF
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ["pickle", "json", "msgpack", "yaml"]
CELERY_TASK_IGNORE_RESULT = False
CELERY_TIME_ZONE = "Europe/Paris"
CELERY_ENABLE_UTC = False
# this allows you to schedule items in the Django admin.
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

# DJANGO-WIKI CONFIGURATION
WIKI_ACCOUNT_HANDLING = True
WIKI_ACCOUNT_SIGNUP_ALLOWED = False
