"""
Django settings for sbadmin project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import shutil

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'q2sb*vqltbpi59f#l2c&mak*%h&xzv1)i^#e0_as^cmx^-9)8x'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
#
# ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'ckeditor',
    'tempus_dominus',
    'bootstrap_modal_forms',
    'widget_tweaks',
    'constance.backends.database',
    'constance',

    # My apps
    'dashboard.apps.DashboardConfig',
    'raspeedi.apps.RaspeediConfig',
    'squalaetp.apps.SqualaetpConfig',
    'reman.apps.RemanConfig',
    'demo.apps.DemoConfig',
    'tools.apps.ToolsConfig',
    'api.apps.ApiConfig',
    'import_export.apps.ImportExportConfig',
    'psa.apps.PsaConfig',
    'ford.apps.FordConfig',
    'renault.apps.RenaultConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',
]

ROOT_URLCONF = 'sbadmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(os.path.dirname(BASE_DIR), 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'sbadmin.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# API REST Framework
# https://www.django-rest-framework.org

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'api.utils.TokenAuthSupportQueryString',
    ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
}

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'fr'
TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True

gettext = lambda x: x

LANGUAGES = (
    ('fr', gettext('French')),
    ('en', gettext('English')),
)

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(os.path.dirname(BASE_DIR), "static"),
)

MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'media')

LOGIN_REDIRECT_URL = '/dashboard/charts/'
LOGOUT_REDIRECT_URL = '/'

# Configuration CkEditor
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'width': 760,
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', '-', 'CopyFormatting', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter',
             'JustifyRight', 'JustifyBlock'],
            ['TextColor', 'BGColor', '-', 'Link', 'Unlink', 'Anchor'],
            ['Scayt', '-', 'Source']
        ],
    }
}

# Configuration Tempus Dominus
TEMPUS_DOMINUS_LOCALIZE = True
TEMPUS_DOMINUS_INCLUDE_ASSETS = False

# Configuration files for Clarion
CONF_FILE = os.path.join(os.path.dirname(BASE_DIR), 'utils/conf/current.py')
CONF_DEFAULT_FILE = os.path.join(os.path.dirname(BASE_DIR), 'utils/conf/default.py')

if not os.path.exists(CONF_FILE):
    shutil.copyfile(CONF_DEFAULT_FILE, CONF_FILE)

# Configuration DJANGO-CONSTANCE
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_CONFIG = {
    # General Options
    'SITE_NAME': ('CSD Dashboard', 'Website title'),
    'SITE_DESCRIPTION': ('', 'Website description'),

    # REMAN Options
    'ECU_TO_EMAIL_LIST': ('test1@test.com; test2@test.com', 'REMAN to email list'),
    'ECU_CC_EMAIL_LIST': ('', 'REMAN Cc email list'),

    # Network Options
    'BASE_DIR': ('~/Documents/CSD_DATABASE', 'Network drive path'),
    'XLS_RASPEEDI_FILE': ('PROG/RASPEEDI/table_boitier_PSA.xlsx', 'xls raspeedi file'),
    'XLS_SQUALAETP_FILE': ('EXTS/squalaetp.xls', 'xls squalaetp file'),
    'XLS_ATTRIBUTS_FILE': ('EXTS/Attributs CORVET.xlsx', 'xls attributs file'),
    'CSV_EXTRACTION_FILE': ('EXTS/extraction.csv', 'csv extraction file'),
    'XLS_ECU_REF_BASE': ('REMAN/PSA/Base réf REMAN.xlsx', 'xls ECU ref base'),
    'XLS_DELAY_PATH': ('RH/AnalyseRetards', 'Path of xls delay files'),
    'XLS_DELAY_FILES': (
        'PSA.xls, ILOTAUTRE.xls, LaboQual.xls, DEFAUT.xls, CLARION.xls', 'List of xls delay file'
    ),

    # MQTT Options
    "MQTT_TOPIC": ('TEMP/TC-01', 'Topic subcribe'),
    'MQTT_TEMP_ADJ': (4, 'Temp adjust', int),
    'MQTT_CLIENT': ('', 'Client name'),
    'MQTT_USER': ('', 'Login'),
    'MQTT_PSWD': ('', 'Password'),
    'MQTT_BROKER': ('test.mosquitto.org', 'Server address'),
    'MQTT_PORT': (1883, 'Server port', int),
    'KEEP_ALIVE': (45, 'Keep alive', int),

    # tools Options
    'PRINTER_STREAM_URL': ('http://10.115.141.42:8080/?action=stream', '3D printer streaming URL')
}

CONSTANCE_CONFIG_FIELDSETS = {
    'General Options': ('SITE_NAME', 'SITE_DESCRIPTION'),
    'REMAN Options': ('ECU_TO_EMAIL_LIST', 'ECU_CC_EMAIL_LIST'),
    'Network Options': (
        'BASE_DIR', 'XLS_RASPEEDI_FILE', 'XLS_SQUALAETP_FILE', 'XLS_ATTRIBUTS_FILE', 'CSV_EXTRACTION_FILE',
        'XLS_ECU_REF_BASE', 'XLS_DELAY_PATH', 'XLS_DELAY_FILES'
    ),
    'MQTT Options': (
        'MQTT_TOPIC', 'MQTT_TEMP_ADJ', 'MQTT_CLIENT', 'MQTT_USER', 'MQTT_PSWD', 'MQTT_BROKER', 'MQTT_PORT', 'KEEP_ALIVE'
    ),
    'Tools Options': (
        'PRINTER_STREAM_URL',
    )
}
