# Generated by Django 3.1.2 on 2020-11-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.CharField(blank=True, choices=[('N/A', 'Vide'), ('HDD', 'Disque Dur'), ('EMMC', 'eMMC'), ('8Go', 'Carte SD 8Go'), ('16Go', 'Carte SD 16Go'), ('8Go 16Go', 'Carte SD 8 ou 16 Go')], max_length=20, verbose_name='type de média'),
        ),
    ]
