# Generated by Django 3.1.2 on 2020-11-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raspeedi', '0010_auto_20200403_1248'),
        ('psa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('reference', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='référence boîtier')),
                ('name', models.CharField(choices=[('RT4', 'RT4'), ('RT5', 'RT5'), ('RT6', 'RT6'), ('RT6v2', 'RT6 version 2'), ('SMEG', 'SMEG'), ('SMEGP', 'SMEG+ / SMEG+ IV1'), ('SMEGP2', 'SMEG+ IV2')], max_length=20, verbose_name='produit')),
                ('front', models.CharField(max_length=2, verbose_name='façade')),
                ('type', models.CharField(choices=[('RAD', 'Radio'), ('NAV', 'Navigation')], max_length=3, verbose_name='type')),
                ('dab', models.BooleanField(default=False, verbose_name='DAB')),
                ('cam', models.BooleanField(default=False, verbose_name='caméra de recul')),
                ('cd_version', models.CharField(blank=True, max_length=10, verbose_name='version CD')),
                ('media', models.CharField(blank=True, choices=[('N/A', 'Vide'), ('HDD', 'Disque Dur'), ('8Go', 'Carte SD 8Go'), ('16Go', 'Carte SD 16Go'), ('8Go 16Go', 'Carte SD 8 ou 16 Go')], max_length=20, verbose_name='type de média')),
                ('carto', models.CharField(blank=True, max_length=20, verbose_name='version cartographie')),
                ('mm_ref', models.CharField(blank=True, max_length=200, verbose_name='référence MM')),
                ('screen_con', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')], null=True, verbose_name="nombre de connecteur d'écran")),
                ('corvets', models.ManyToManyField(blank=True, related_name='products', to='psa.Corvet')),
                ('raspeedi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raspeedi.raspeedi')),
            ],
            options={
                'verbose_name': 'Données Produit',
                'ordering': ['reference'],
            },
        ),
    ]
