# Generated by Django 3.2.18 on 2023-03-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0002_auto_20230215_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvet',
            name='electronique_11q',
            field=models.CharField(blank=True, max_length=200, verbose_name='DMTX_HARD - DISPOSITIF MAINTIEN TENSION'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_14e',
            field=models.CharField(blank=True, max_length=200, verbose_name='HARD - NAVIGATION Abandonne'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_1f4',
            field=models.CharField(blank=True, max_length=200, verbose_name='SDCM_HARD - BOITIER DE GESTION DES COMMUNICATIONS A COURTES DISTANCES'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_1j6',
            field=models.CharField(blank=True, max_length=200, verbose_name='HARD - DETECTION PRESENCE DES MAINS SUR LE VOLANT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_1j8',
            field=models.CharField(blank=True, max_length=200, verbose_name='CAMERA FRONTALE MULTIFONCTIONS'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_1j9',
            field=models.CharField(blank=True, max_length=200, verbose_name='HARD - FRONT RADAR'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_1k4',
            field=models.CharField(blank=True, max_length=200, verbose_name='VSM_HARD - MODULE SUPERVISION VEHICULE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_1k5',
            field=models.CharField(blank=True, max_length=200, verbose_name='HARD - VEHICLE COMPARTMENT CONTROL UNIT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_1k9',
            field=models.CharField(blank=True, max_length=200, verbose_name='HARD - RECONFIGURABLE TOUCH SCREEN'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_1l9',
            field=models.CharField(blank=True, max_length=200, verbose_name='BOITIER SERVITUDE RADIO FREQUENCE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_1m2',
            field=models.CharField(blank=True, max_length=200, verbose_name='IN-VEHICULE INFOTAINMENT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_34r',
            field=models.CharField(blank=True, max_length=200, verbose_name='AAS SOFT LIVRE - Aide Au Stationnement'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_3f4',
            field=models.CharField(blank=True, max_length=200, verbose_name='SDCM_SOFT.LIVRE - BOITIER DE GESTION DES COMMUNICATIONS A COURTES DISTANCES'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_3j8',
            field=models.CharField(blank=True, max_length=200, verbose_name='CAMERA FRONTALE MULTIFONCTIONS'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_3j9',
            field=models.CharField(blank=True, max_length=200, verbose_name='DELIVERED SOFT. - FRONT RADAR'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_3k5',
            field=models.CharField(blank=True, max_length=200, verbose_name='DELIVERED SOFT. - VEHICLE COMPARTMENT CONTROL UNIT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_3l9',
            field=models.CharField(blank=True, max_length=200, verbose_name='BOITIER SERVITUDE RADIO FREQUENCE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_3m2',
            field=models.CharField(blank=True, max_length=200, verbose_name='IN-VEHICULE INFOTAINMENT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_41q',
            field=models.CharField(blank=True, max_length=200, verbose_name='DMTX_FOURN.NO.SERIE - DISPOSITIF MAINTIEN TENSION'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_44e',
            field=models.CharField(blank=True, max_length=200, verbose_name='FOURN.NO.SERIE - NAVIGATION Abandonne'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_4j8',
            field=models.CharField(blank=True, max_length=200, verbose_name='CAMERA FRONTALE MULTIFONCTIONS'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_4l9',
            field=models.CharField(blank=True, max_length=200, verbose_name='BOITIER SERVITUDE RADIO FREQUENCE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_4m2',
            field=models.CharField(blank=True, max_length=200, verbose_name='IN-VEHICULE INFOTAINMENT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_51q',
            field=models.CharField(blank=True, max_length=200, verbose_name='DMTX_FOURN.DATE.FAB - DISPOSITIF MAINTIEN TENSION'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_54e',
            field=models.CharField(blank=True, max_length=200, verbose_name='FOURN.DATE.FAB - NAVIGATION Abandonne'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_5j6',
            field=models.CharField(blank=True, max_length=200, verbose_name='FOURN.DATE.FAB - DETECTION PRESENCE DES MAINS SUR LE VOLANT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_5j8',
            field=models.CharField(blank=True, max_length=200, verbose_name='CAMERA FRONTALE MULTIFONCTIONS'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_5j9',
            field=models.CharField(blank=True, max_length=200, verbose_name='SUPPLIER DATE - FRONT RADAR'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_5m2',
            field=models.CharField(blank=True, max_length=200, verbose_name='IN-VEHICULE INFOTAINMENT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_61q',
            field=models.CharField(blank=True, max_length=200, verbose_name='DMTX_FOURN.CODE - DISPOSITIF MAINTIEN TENSION'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_64e',
            field=models.CharField(blank=True, max_length=200, verbose_name='FOURN.CODE - NAVIGATION Abandonne'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_6j6',
            field=models.CharField(blank=True, max_length=200, verbose_name='FOURN.CODE - DETECTION PRESENCE DES MAINS SUR LE VOLANT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_6j8',
            field=models.CharField(blank=True, max_length=200, verbose_name='CAMERA FRONTALE MULTIFONCTIONS'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_6j9',
            field=models.CharField(blank=True, max_length=200, verbose_name='SUPPLIER CODE - FRONT RADAR'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_6k4',
            field=models.CharField(blank=True, max_length=200, verbose_name='VSM_FOURN.CODE - MODULE SUPERVISION VEHICULE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_6k5',
            field=models.CharField(blank=True, max_length=200, verbose_name='SUPPLIER CODE - VEHICLE COMPARTMENT CONTROL UNIT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_6k9',
            field=models.CharField(blank=True, max_length=200, verbose_name='SUPPLIER CODE - RECONFIGURABLE TOUCH SCREEN'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_6l9',
            field=models.CharField(blank=True, max_length=200, verbose_name='BOITIER SERVITUDE RADIO FREQUENCE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_6m2',
            field=models.CharField(blank=True, max_length=200, verbose_name='IN-VEHICULE INFOTAINMENT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_8j8',
            field=models.CharField(blank=True, max_length=200, verbose_name='CAMERA FRONTALE MULTIFONCTIONS'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_8j9',
            field=models.CharField(blank=True, max_length=200, verbose_name='DOTE - FRONT RADAR'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_8k4',
            field=models.CharField(blank=True, max_length=200, verbose_name='VSM_DOTE - MODULE SUPERVISION VEHICULE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_8l9',
            field=models.CharField(blank=True, max_length=200, verbose_name='BOITIER SERVITUDE RADIO FREQUENCE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_8m2',
            field=models.CharField(blank=True, max_length=200, verbose_name='IN-VEHICULE INFOTAINMENT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_91q',
            field=models.CharField(blank=True, max_length=200, verbose_name='DMTX_SOFT - DISPOSITIF MAINTIEN TENSION'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_9f4',
            field=models.CharField(blank=True, max_length=200, verbose_name='SDCM_SOFT - BOITIER DE GESTION DES COMMUNICATIONS A COURTES DISTANCES'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_9j8',
            field=models.CharField(blank=True, max_length=200, verbose_name='CAMERA FRONTALE MULTIFONCTIONS'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_9j9',
            field=models.CharField(blank=True, max_length=200, verbose_name='SOFT. - FRONT RADAR'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_9k4',
            field=models.CharField(blank=True, max_length=200, verbose_name='VSM_SOFT - MODULE SUPERVISION VEHICULE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_9k5',
            field=models.CharField(blank=True, max_length=200, verbose_name='SOFT. - VEHICLE COMPARTMENT CONTROL UNIT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_9l9',
            field=models.CharField(blank=True, max_length=200, verbose_name='BOITIER SERVITUDE RADIO FREQUENCE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_kl9',
            field=models.CharField(blank=True, max_length=200, verbose_name='BSRF - NUMERO IMEI: INTERNATIONAL MOBILE EQUIPMENT IDENTITY'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_ml9',
            field=models.CharField(blank=True, max_length=200, verbose_name='BSRF - NUMERO IMSI: INTERNATIONAL MOBILE SUBSCRIBER IDENTITY'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_p4d',
            field=models.CharField(blank=True, max_length=200, verbose_name='BVA EOBD - Boitier Arret et Démarrage Moteur (STOP & START)'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_rl9',
            field=models.CharField(blank=True, max_length=200, verbose_name='BSRF - NUMERO ICCID: INTEGRATED CICUIT CARD ID'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_tj8',
            field=models.CharField(blank=True, max_length=200, verbose_name='FRONT CAMERA PARAMETRES D APPRENTISSAGE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_vj8',
            field=models.CharField(blank=True, max_length=200, verbose_name='FRONT CAMERA HAUTEUR SOUS BERCEAU'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_xm2',
            field=models.CharField(blank=True, max_length=200, verbose_name='DATA LIBRARY - IVI - IN-VEHICULE INFOTAINMENT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_yl9',
            field=models.CharField(blank=True, max_length=200, verbose_name='VEHICLE APP - BSRF - BOITIER SERVITUDE RADIO FREQUENCE'),
        ),
    ]
