# Generated by Django 3.1.2 on 2020-11-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.CharField(max_length=18, unique=True, verbose_name='SWL(UpdateID)')),
                ('version', models.CharField(max_length=200, verbose_name='UpdateVersion')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='UpdateType')),
                ('version_date', models.DateField(blank=True, null=True, verbose_name='MediaVersionDate')),
                ('ecu_type', models.CharField(choices=[('NAC_EUR_WAVE2', 'NAC_EUR_WAVE2'), ('NAC_EUR_WAVE1', 'NAC_EUR_WAVE1'), ('NAC_EUR_WAVE3', 'NAC_EUR_WAVE3'), ('NAC_EUR_WAVE4', 'NAV_EUR_WAVE4')], max_length=50, verbose_name='EcuType')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='lien de téléchargement')),
                ('is_active', models.BooleanField(default=False, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'Firmwares Télématique',
                'ordering': ['update_id'],
            },
        ),
    ]
