# Generated by Django 3.2.18 on 2023-03-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0003_auto_20230324_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCode',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=200, verbose_name='nom fournisseur')),
            ],
            options={
                'verbose_name': 'Code Fournisseur',
                'ordering': ['code'],
            },
        ),
    ]
