# Generated by Django 3.1.2 on 2020-11-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0003_auto_20201112_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(max_length=10, unique=True, verbose_name='version usine')),
                ('type', models.CharField(choices=[('94B', 'BSI SOFT - Boitier Servitude Intelligent'), ('94A', 'CMM SOFT - Calculateur Moteur Multifonction'), ('94F', 'RADIO SOFT - Recepteur Radio'), ('94L', 'EMF SOFT - Ecran Multifonctions'), ('94X', 'BTEL SOFT - Boitier Telematique'), ('96B', 'BSM SOFT - Boitier Servitude Moteur'), ('99H', 'MDS SOFT - Module de service telematique')], max_length=3, verbose_name='type')),
                ('current', models.CharField(blank=True, max_length=10, verbose_name='version actuelle')),
            ],
            options={
                'verbose_name': 'Calibration',
                'ordering': ['-factory'],
            },
        ),
    ]
