# Generated by Django 3.1.2 on 2020-11-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0003_firmware'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmware',
            options={'ordering': ['-update_id'], 'verbose_name': 'Firmwares Télématique'},
        ),
    ]
