# Generated by Django 3.1.2 on 2020-11-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0004_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorvetChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='clé')),
                ('value', models.CharField(max_length=200, verbose_name='valeur')),
                ('column', models.CharField(choices=[('DON_LIN_PROD', 'donnee_ligne_de_produit'), ('DON_MAR_COMM', 'donnee_marque_commerciale'), ('DON_SIL', 'donnee_silhouette'), ('DON_GEN_PROD', 'donnee_genre_de_produit'), ('ATT_DGM', 'COMBINE (CARACTERISTIQUES)'), ('ATT_DHB', 'HAUT PARLEUR'), ('ATT_DAT', 'ANTENNE'), ('ATT_DCX', 'COTE CONDUITE/POSTE CONDUITE'), ('DON_MOT', 'MOTEUR'), ('DON_TRA', 'TRANSMISSION')], max_length=100, verbose_name='colonne')),
            ],
            options={
                'verbose_name': 'Convertion données CORVET',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dcx',
            field=models.CharField(blank=True, max_length=200, verbose_name='COTE CONDUITE/POSTE CONDUITE'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='donnee_date_debut_garantie',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date début garantie'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='donnee_date_entree_montage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date entrée montage'),
        ),
        migrations.AddConstraint(
            model_name='corvetchoices',
            constraint=models.UniqueConstraint(fields=('key', 'column'), name='key_column_unique'),
        ),
    ]
