# Generated by Django 3.1.2 on 2020-11-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0005_auto_20201119_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('hw_reference', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='référence HW')),
                ('name', models.CharField(choices=[('RD3', 'RD3'), ('RD45', 'RD45'), ('RD5', 'RD5'), ('RDE', 'RDE'), ('RT3', 'RT3'), ('RT4', 'RT4'), ('RT5', 'RT5'), ('RT6', 'RT6 / RNEG2'), ('RT6v2', 'RT6v2 / RNEG2'), ('SMEG', 'SMEG'), ('SMEGP', 'SMEG+ / SMEG+ IV1'), ('SMEGP2', 'SMEG+ IV2'), ('NG4', 'NG4'), ('RNEG', 'RNEG'), ('NAC1', 'NAC wave1'), ('NAC2', 'NAC wave2'), ('NAC3', 'NAC wave3'), ('NAC4', 'NAC wave4')], max_length=20, verbose_name='modèle')),
                ('oe_reference', models.CharField(blank=True, max_length=200, verbose_name='référence OEM')),
                ('supplier_oe', models.CharField(blank=True, max_length=50, verbose_name='fabriquant')),
                ('type', models.CharField(choices=[('RAD', 'Radio'), ('NAV', 'Navigation')], max_length=3, verbose_name='type')),
                ('level', models.CharField(blank=True, max_length=2, verbose_name='niveau')),
                ('extra', models.CharField(blank=True, max_length=100, verbose_name='supplément')),
                ('dab', models.BooleanField(default=False, verbose_name='DAB')),
                ('cam', models.BooleanField(default=False, verbose_name='caméra de recul')),
                ('cd_player', models.BooleanField(default=False, verbose_name='lecteur CD')),
                ('jukebox', models.BooleanField(default=False, verbose_name='jukebox')),
                ('media', models.CharField(blank=True, choices=[('N/A', 'Vide'), ('HDD', 'Disque Dur'), ('EMMC', 'eMMC'), ('external SD', 'Carte SD Externe'), ('8Go', 'Carte SD 8Go'), ('16Go', 'Carte SD 16Go'), ('8Go 16Go', 'Carte SD 8 ou 16 Go')], max_length=20, verbose_name='type de média')),
                ('lvds_con', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')], null=True, verbose_name="nombre d'LVDS")),
                ('usb_con', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True, verbose_name="nombre d'USB")),
                ('front_pic', models.ImageField(blank=True, upload_to='psa')),
                ('setplate_pic', models.ImageField(blank=True, upload_to='psa')),
                ('rear_pic', models.ImageField(blank=True, upload_to='psa')),
            ],
            options={
                'verbose_name': 'Données Multimédia',
                'ordering': ['hw_reference'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
