# Generated by Django 3.2.19 on 2023-06-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0005_auto_20230329_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('family', models.CharField(choices=[('MULTIMEDIA', 'Multimédia'), ('ECU', 'Calculateur')], max_length=50, verbose_name='Famille')),
                ('short_name', models.CharField(max_length=20, verbose_name='Nom court')),
                ('ecu_type', models.CharField(max_length=10, verbose_name='Type ECU')),
                ('cal_attribute', models.CharField(blank=True, max_length=3, verbose_name='Attribut CAL')),
            ],
        ),
        migrations.AddField(
            model_name='corvetproduct',
            name='ivi',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'NAV'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corvet_ivi', to='psa.multimedia'),
        ),
        migrations.AlterField(
            model_name='ecu',
            name='type',
            field=models.CharField(choices=[('BSI', 'Boitier Servitude Intelligent'), ('BSM', 'Boitier Servitude Moteur'), ('CMB', 'Combine Planche de Bord'), ('CMM', 'Calculateur Moteur Multifonction'), ('EMF', 'Ecran Multifonctions'), ('FMUX', 'Façade Multiplexée'), ('HDC', 'Haut de Colonne de Direction (COM200x)'), ('MDS', 'Module de service telematique'), ('CVM2', 'Camera Video Multifonction V2'), ('VMF', 'Module Commutation Integre'), ('DMTX', 'Dispositif Maintien Tension')], max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='name',
            field=models.CharField(blank=True, choices=[('RD3', 'RD3'), ('RD4', 'RD4'), ('RD45', 'RD45'), ('RD5', 'RD5'), ('RDE', 'RDE'), ('RT3', 'RT3'), ('RT4', 'RT4'), ('RT5', 'RT5'), ('RT6', 'RT6 / RNEG2'), ('RT6v2', 'RT6v2 / RNEG2'), ('SMEG', 'SMEG'), ('SMEGP', 'SMEG+ / SMEG+ IV1'), ('SMEGP2', 'SMEG+ IV2'), ('NG4', 'NG4'), ('RNEG', 'RNEG'), ('RCC', 'RCC'), ('NAC1', 'NAC wave1'), ('NAC2', 'NAC wave2'), ('NAC3', 'NAC wave3'), ('NAC4', 'NAC wave4'), ('IVI', 'In-Vehicle Infotainment')], max_length=20, verbose_name='modèle'),
        ),
        migrations.AddField(
            model_name='ecu',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecus', to='psa.productchoice'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='psa.productchoice'),
        ),
    ]
