# Generated by Django 3.1.2 on 2020-11-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0006_auto_20201122_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='ant_con',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True, verbose_name="Nombre d'antenne"),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='carplay',
            field=models.BooleanField(null=True, verbose_name='CarPlay'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='hw_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='type HW'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='label_ref',
            field=models.CharField(blank=True, max_length=10, verbose_name='réf. étiquette'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='jukebox',
            field=models.BooleanField(null=True, verbose_name='jukebox'),
        ),
    ]
