# Generated by Django 3.2.19 on 2023-06-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0006_auto_20230606_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='code')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('type', models.CharField(max_length=2, verbose_name='type')),
                ('characterization', models.CharField(blank=True, max_length=500, verbose_name='caractérisation')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='localisation')),
                ('help', models.CharField(blank=True, max_length=500, verbose_name='aide')),
                ('ecu_type', models.CharField(max_length=100, verbose_name='type ECU')),
            ],
            options={
                'verbose_name': 'Code Defaut',
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='defaultcode',
            constraint=models.UniqueConstraint(fields=('code', 'type', 'ecu_type'), name='Default code unique'),
        ),
    ]
