# Generated by Django 3.2.19 on 2023-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0007_auto_20230609_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchoice',
            name='protocol',
            field=models.CharField(blank=True, choices=[('AEE2004', 'AEE2004'), ('AEE2010', 'AEE2010')], max_length=100, verbose_name='Protocole'),
        ),
    ]
