# Generated by Django 3.1.3 on 2020-12-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0008_auto_20201125_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corvetchoices',
            name='column',
            field=models.CharField(choices=[('DON_LIN_PROD', 'donnee_ligne_de_produit'), ('DON_MAR_COMM', 'donnee_marque_commerciale'), ('DON_SIL', 'donnee_silhouette'), ('DON_GEN_PROD', 'donnee_genre_de_produit'), ('ATT_DGM', 'COMBINE (CARACTERISTIQUES)'), ('ATT_DHB', 'HAUT PARLEUR'), ('ATT_DHG', 'COMMANDE AUTO-RADIO'), ('ATT_DJY', 'SYSTEME NAVIGATION'), ('ATT_DLX', 'AFFICHEUR AV'), ('ATT_DYM', 'PRISE AUXILIAIRE PACK AUDIO'), ('ATT_DYR', 'BOITIER TELEMATIQUE'), ('ATT_DAT', 'ANTENNE'), ('ATT_DCX', 'COTE CONDUITE/POSTE CONDUITE'), ('DON_MOT', 'MOTEUR'), ('DON_TRA', 'TRANSMISSION'), ('ELE_14R', 'AAS HARD - Aide Au Stationnement')], max_length=100, verbose_name='colonne'),
        ),
    ]
