# Generated by Django 3.2.19 on 2023-08-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0008_productchoice_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvet',
            name='electronique_11n',
            field=models.CharField(blank=True, max_length=200, verbose_name='BPGA HARD BOITIER PROTECTION ALIMENT RESEAU ELEC [FR]'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_41n',
            field=models.CharField(blank=True, max_length=200, verbose_name='BPGA FOURN.NO.SERIE BOITIER PROTECT ALIMENT RESEAU ELEC[FR]'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_51n',
            field=models.CharField(blank=True, max_length=200, verbose_name='BPGA FOURN.DATE.FAB- BOITIER PROTECT ALIMENT RESEAU ELEC[FR]'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_61n',
            field=models.CharField(blank=True, max_length=200, verbose_name='BPGA FOURN.CODE - BOITIER PROTECTION ALIMENT RESEAU ELEC[FR]'),
        ),
    ]
