# Generated by Django 3.1.4 on 2020-12-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0009_auto_20201204_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvet',
            name='btel',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'NAV'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corvet_btel', to='psa.multimedia'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='radio',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'RAD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corvet_radio', to='psa.multimedia'),
        ),
    ]
