# Generated by Django 3.1.6 on 2021-02-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0010_auto_20201223_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='BsiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=13, unique=True, verbose_name='reference PSA')),
                ('name', models.CharField(max_length=50, verbose_name='modèle')),
                ('hw', models.CharField(blank=True, max_length=10, verbose_name='HW')),
                ('sw', models.CharField(blank=True, max_length=10, verbose_name='SW')),
                ('supplier_oe', models.CharField(blank=True, max_length=50, verbose_name='fabriquant')),
            ],
            options={
                'verbose_name': 'Données BSI',
                'ordering': ['reference'],
            },
        ),
        migrations.AddField(
            model_name='corvet',
            name='bsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corvet_bsi', to='psa.bsimodel'),
        ),
    ]
