# Generated by Django 3.2.20 on 2023-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0010_auto_20230915_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='modèle')),
                ('brand', models.CharField(max_length=50, verbose_name='fabriquant')),
            ],
        ),
        migrations.RemoveField(
            model_name='canremote',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='canremote',
            name='corvets',
        ),
        migrations.RemoveField(
            model_name='canremote',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='canremote',
            name='dlc',
            field=models.IntegerField(default=8, verbose_name='DLC'),
        ),
        migrations.AddConstraint(
            model_name='canremote',
            constraint=models.UniqueConstraint(fields=('label', 'type', 'can_id', 'data'), name='Can remote unique'),
        ),
        migrations.AddField(
            model_name='canremote',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='psa.Vehicle'),
        ),
    ]
