# Generated by Django 3.2.20 on 2023-09-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0011_auto_20230922_1250'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='canremote',
            name='Can remote unique',
        ),
        migrations.AddConstraint(
            model_name='canremote',
            constraint=models.UniqueConstraint(fields=('label', 'type', 'product', 'can_id', 'data'), name='Can remote unique'),
        ),
    ]
