# Generated by Django 3.1.6 on 2021-02-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0011_auto_20210210_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmfModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_reference', models.CharField(max_length=10, unique=True, verbose_name='référence HW')),
                ('name', models.CharField(max_length=50, verbose_name='modèle')),
                ('hw', models.CharField(blank=True, max_length=10, verbose_name='HW')),
                ('sw', models.CharField(blank=True, max_length=10, verbose_name='SW')),
                ('supplier_oe', models.CharField(blank=True, max_length=50, verbose_name='fabriquant')),
                ('pr_reference', models.CharField(blank=True, max_length=10, verbose_name='référence PR')),
            ],
            options={
                'verbose_name': 'Données EMF',
                'ordering': ['hw_reference'],
            },
        ),
        migrations.AddField(
            model_name='corvet',
            name='emf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corvet_emf', to='psa.emfmodel'),
        ),
    ]
