# Generated by Django 3.1.7 on 2021-03-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0012_auto_20210211_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsimodel',
            name='pr_reference',
            field=models.CharField(blank=True, max_length=10, verbose_name='référence PR'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='pr_reference',
            field=models.CharField(blank=True, max_length=10, verbose_name='référence PR'),
        ),
    ]
