# Generated by Django 3.1.7 on 2021-03-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0013_auto_20210331_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='firmware',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psa.firmware'),
        ),
    ]
