# Generated by Django 3.2.22 on 2023-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0013_auto_20231106_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcode',
            name='description',
            field=models.CharField(max_length=500, verbose_name='description'),
        ),
    ]
