# Generated by Django 3.2.23 on 2024-01-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0015_auto_20240105_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='type',
            field=models.CharField(max_length=3, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='ecu',
            name='type',
            field=models.CharField(max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='ecu_type',
            field=models.CharField(max_length=50, verbose_name='EcuType'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='modèle'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='type',
            field=models.CharField(max_length=3, verbose_name='type'),
        ),
    ]
