# Generated by Django 3.2.25 on 2024-05-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0016_auto_20240117_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productchoice',
            options={'ordering': ['name'], 'verbose_name': 'Choix produit'},
        ),
        migrations.AddField(
            model_name='productchoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psa.suppliercode'),
        ),
        migrations.AddField(
            model_name='productchoice',
            name='uce_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='UCE Code'),
        ),
        migrations.AddField(
            model_name='productchoice',
            name='unlock_key',
            field=models.CharField(blank=True, max_length=4, verbose_name='Unlock Key'),
        ),
        migrations.AddConstraint(
            model_name='productchoice',
            constraint=models.UniqueConstraint(fields=('name', 'uce_code', 'unlock_key', 'supplier'), name='Product choice unique'),
        ),
    ]
