# Generated by Django 3.2 on 2021-04-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0016_auto_20210413_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corvet',
            name='emf',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'EMF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corvet_emf', to='psa.ecu'),
        ),
    ]
