# Generated by Django 3.2 on 2021-04-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0017_alter_corvet_emf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmfModel',
        ),
    ]
