# Generated by Django 3.2.25 on 2024-05-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0017_auto_20240516_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecu',
            name='product',
            field=models.ForeignKey(blank=True, limit_choices_to={'family': 'ECU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecus', to='psa.productchoice'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='product',
            field=models.ForeignKey(blank=True, limit_choices_to={'family': 'MULTIMEDIA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='psa.productchoice'),
        ),
    ]
