# Generated by Django 3.2.25 on 2024-05-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0018_auto_20240516_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='disponible'),
        ),
    ]
