# Generated by Django 3.2.3 on 2021-06-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0019_auto_20210603_1606'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO psa_corvetproduct (
                corvet_id,
                btel_id,
                radio_id,
                bsi_id,
                emf_id,
                bsm_id,
                cmm_id
            )
            SELECT
                vin,
                btel_id,
                radio_id,
                bsi_id,
                emf_id,
                bsm_id,
                cmm_id
            FROM
                psa_corvet;
        """, reverse_sql=migrations.RunSQL.noop)
    ]
