# Generated by Django 3.2.25 on 2024-06-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('psa', '0019_calibration_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='version actuelle')),
                ('type', models.CharField(max_length=3, verbose_name='type')),
                ('pr_reference', models.CharField(blank=True, max_length=10, verbose_name='référence PR')),
                ('is_available', models.BooleanField(default=False, verbose_name='disponible')),
            ],
            options={
                'verbose_name': 'Cal. actuelle',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='CalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='version actuelle')),
                ('pr_reference', models.CharField(blank=True, max_length=10, verbose_name='référence PR')),
                ('is_available', models.BooleanField(default=False, verbose_name='disponible')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Cal. historique',
                'ordering': ['-name'],
            },
        ),
    ]
