# Generated by Django 3.2.4 on 2021-06-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0020_auto_20210603_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corvet',
            name='bsi',
        ),
        migrations.RemoveField(
            model_name='corvet',
            name='bsm',
        ),
        migrations.RemoveField(
            model_name='corvet',
            name='btel',
        ),
        migrations.RemoveField(
            model_name='corvet',
            name='cmm',
        ),
        migrations.RemoveField(
            model_name='corvet',
            name='emf',
        ),
        migrations.RemoveField(
            model_name='corvet',
            name='radio',
        ),
    ]
