# Generated by Django 3.2.25 on 2024-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0020_calcurrent_calhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvetoption',
            name='new_44f',
            field=models.CharField(blank=True, max_length=200, verbose_name='new_44f'),
        ),
        migrations.AddField(
            model_name='corvetoption',
            name='new_44x',
            field=models.CharField(blank=True, max_length=200, verbose_name='new_44x'),
        ),
    ]
