# Generated by Django 3.2.25 on 2024-09-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0021_auto_20240607_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvetproduct',
            name='aas',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'AAS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corvet_aas', to='psa.ecu'),
        ),
    ]
