# Generated by Django 3.2.4 on 2021-06-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0021_auto_20210607_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvet',
            name='attribut_dao',
            field=models.CharField(blank=True, max_length=200, verbose_name='SURVEILLANCE VOIE LATERALE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_dcd',
            field=models.CharField(blank=True, max_length=200, verbose_name='CARBURANT (RON MINI MOTEUR)'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_de2',
            field=models.CharField(blank=True, max_length=200, verbose_name='MIRROR LINK'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_de3',
            field=models.CharField(blank=True, max_length=200, verbose_name='RECHARGE NOMADE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_de4',
            field=models.CharField(blank=True, max_length=200, verbose_name='JUKE BOX'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_dpr',
            field=models.CharField(blank=True, max_length=200, verbose_name='PROJECTEUR ANTI-BROUILLARD'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_dqk',
            field=models.CharField(blank=True, max_length=200, verbose_name='AIDE VISUELLE PANORAMIQUE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_dqp',
            field=models.CharField(blank=True, max_length=200, verbose_name='AFFICHAGE COMPL DETECTION EXT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_dub',
            field=models.CharField(blank=True, max_length=200, verbose_name='DETECTION OBSTACLE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_due',
            field=models.CharField(blank=True, max_length=200, verbose_name='DETECTION SOUS GONFLAGE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_duf',
            field=models.CharField(blank=True, max_length=200, verbose_name='SYSTEME ESP/ESC'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_dyc',
            field=models.CharField(blank=True, max_length=200, verbose_name='STOP AND START'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_dyq',
            field=models.CharField(blank=True, max_length=200, verbose_name='ALLUMAGE FEUX'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_dze',
            field=models.CharField(blank=True, max_length=200, verbose_name='PACK VISION'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_11m',
            field=models.CharField(blank=True, max_length=200, verbose_name='VMF HARD - MODULE COMMUTATION INTEGRE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_12y',
            field=models.CharField(blank=True, max_length=200, verbose_name='CVM2_2_ HARD - CAMERA VIDEO MULTIFONCTION V2'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_14d',
            field=models.CharField(blank=True, max_length=200, verbose_name='BV HARD - Boite Vitesses'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_14m',
            field=models.CharField(blank=True, max_length=200, verbose_name='RBG HARD - Boitier Air Bag (Sac Gonflable)'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_14p',
            field=models.CharField(blank=True, max_length=200, verbose_name='FREIN HARD - Frein ABS/ESP/EHB Frein Principal'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_14y',
            field=models.CharField(blank=True, max_length=200, verbose_name='EDP HARD - Electronique De Porte Conducteur'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_14z',
            field=models.CharField(blank=True, max_length=200, verbose_name='EDP_P HARD - Electronique De Porte Passager'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_16g',
            field=models.CharField(blank=True, max_length=200, verbose_name='CDPL HARD - Capteur de pluie/luminosite'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_16l',
            field=models.CharField(blank=True, max_length=200, verbose_name='DAE HARD - Direction Assistee Electrique'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_16q',
            field=models.CharField(blank=True, max_length=200, verbose_name='BCM HARD - Boitier coffre Motorise'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_16t',
            field=models.CharField(blank=True, max_length=200, verbose_name='MOTEV HARD - Moteur Essuie-Vitre'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_16v',
            field=models.CharField(blank=True, max_length=200, verbose_name='BCPM HARD - Projecteur gauche avec fonctionnalites de correction integrees'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_18z',
            field=models.CharField(blank=True, max_length=200, verbose_name='TNB HARD - Boitier de non Bouclage Ceinture Securite'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_19f',
            field=models.CharField(blank=True, max_length=200, verbose_name='BECB HARD - Boitier Electronique Etat charge Batterie'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_19t',
            field=models.CharField(blank=True, max_length=200, verbose_name='PDPC HARD - Platine de Porte Conducteur'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_19u',
            field=models.CharField(blank=True, max_length=200, verbose_name='BEM HARD - Boitier Eclairage Memorisation'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_19v',
            field=models.CharField(blank=True, max_length=200, verbose_name='CRT HARD - Leve Vitre Arriere Droit'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_19w',
            field=models.CharField(blank=True, max_length=200, verbose_name='LVARG HARD - Leve Vitre Arriere Gauche'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_34p',
            field=models.CharField(blank=True, max_length=200, verbose_name='FREIN SOFT LIVRE - Frein ABS/ESP/EHB Frein Principal'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_92y',
            field=models.CharField(blank=True, max_length=200, verbose_name='CVM2_2_ SOFT - CAMERA VIDEO MULTIFONCTION V2'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_94d',
            field=models.CharField(blank=True, max_length=200, verbose_name='BV SOFT - Boite Vitesses'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_94j',
            field=models.CharField(blank=True, max_length=200, verbose_name='CLIM SOFT - Climatisation'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_94k',
            field=models.CharField(blank=True, max_length=200, verbose_name='CMB SOFT - Combine Planche de Bord'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_94m',
            field=models.CharField(blank=True, max_length=200, verbose_name='RBG SOFT - Boitier Air Bag (Sac Gonflable)'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_94p',
            field=models.CharField(blank=True, max_length=200, verbose_name='FREIN SOFT - Frein ABS/ESP/EHB Frein Principal'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_94r',
            field=models.CharField(blank=True, max_length=200, verbose_name='AAS SOFT - Aide Au Stationnement'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_96g',
            field=models.CharField(blank=True, max_length=200, verbose_name='CDPL SOFT - Capteur de pluie/luminosite'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_96l',
            field=models.CharField(blank=True, max_length=200, verbose_name='DAE SOFT - Direction Assistee Electrique'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_96q',
            field=models.CharField(blank=True, max_length=200, verbose_name='BCM SOFT - Boitier coffre Motorise'),
        ),
    ]
