# Generated by Django 4.2.16 on 2024-10-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0022_corvetproduct_aas'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchoice',
            name='firmware',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psa.firmware'),
        ),
    ]
