# Generated by Django 3.2.8 on 2021-11-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0026_alter_multimedia_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvet',
            name='attribut_d5j',
            field=models.CharField(blank=True, max_length=200, verbose_name='VERSIONS RADIO'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_daz',
            field=models.CharField(blank=True, max_length=200, verbose_name='ALIMENTATION'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_dcp',
            field=models.CharField(blank=True, max_length=200, verbose_name='GRADUATION VITESSES'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_ddc',
            field=models.CharField(blank=True, max_length=200, verbose_name='DEPOLLUTION (MOTEUR)'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_de7',
            field=models.CharField(blank=True, max_length=200, verbose_name='AFFICHAGE PANNEAU ROUTIER'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_de8',
            field=models.CharField(blank=True, max_length=200, verbose_name='ALERTE VIGILANCE CONDUCTEUR'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_des',
            field=models.CharField(blank=True, max_length=200, verbose_name='PRISE ACCESSOIRES'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_di2',
            field=models.CharField(blank=True, max_length=200, verbose_name='RECONNAISSANCE VOCALE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_djz',
            field=models.CharField(blank=True, max_length=200, verbose_name='FREQUENCE TELECDE CONDAMNATION'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_dn1',
            field=models.CharField(blank=True, max_length=200, verbose_name='NIGHT VISION'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_dsb',
            field=models.CharField(blank=True, max_length=200, verbose_name='SURVEILLANCE / LIMITATION VIT'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_duo',
            field=models.CharField(blank=True, max_length=200, verbose_name='AFFICHEUR COMPLEMENTAIRE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='attribut_duz',
            field=models.CharField(blank=True, max_length=200, verbose_name='FREQUENCE RADIO'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_12e',
            field=models.CharField(blank=True, max_length=200, verbose_name='AVM - HARD - AIDE VISUELLE A LA MANOEUVRE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_19k',
            field=models.CharField(blank=True, max_length=200, verbose_name='ARTIV HARD - Boitier Aide au Respect du Temps Inter Vehicule'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_42e',
            field=models.CharField(blank=True, max_length=200, verbose_name='AVM - FNR NO SERIE - AIDE VISUELLE A LA MANŒUVRE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_49k',
            field=models.CharField(blank=True, max_length=200, verbose_name='ARTIV FOURN.NO.SERIE - Boitier Aide au Respect du Temps Inter Vehicule'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_52e',
            field=models.CharField(blank=True, max_length=200, verbose_name='AVM - FNR DATE - AIDE VISUELLE A LA MANŒUVRE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_59k',
            field=models.CharField(blank=True, max_length=200, verbose_name='ARTIV FOURN.DATE.FAB - Boitier Aide au Respect du Temps Inter Vehicule'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_62e',
            field=models.CharField(blank=True, max_length=200, verbose_name='AVM - FNR CODE - AIDE VISUELLE A LA MANŒUVRE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_69k',
            field=models.CharField(blank=True, max_length=200, verbose_name='ARTIV FOURN.CODE - Boitier Aide au Respect du Temps Inter Vehicule'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_92e',
            field=models.CharField(blank=True, max_length=200, verbose_name='AVM - SOFT - AIDE VISUELLE A LA MANŒUVRE'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_99k',
            field=models.CharField(blank=True, max_length=200, verbose_name='ARTIV SOFT - Boitier Aide au Respect du Temps Inter Vehicule'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_k9h',
            field=models.CharField(blank=True, max_length=200, verbose_name='BTA - NUMERO IMEI: INTERNATIONAL MOBILE EQUIPMENT IDENTITY'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_m9h',
            field=models.CharField(blank=True, max_length=200, verbose_name='BTA - NUMERO IMSI: INTERNATIONAL MOBILE SUBSCRIBER IDENTITY'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_r9h',
            field=models.CharField(blank=True, max_length=200, verbose_name='BTA - NUMERO ICCID: INTEGRATED CICUIT CARD ID'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_t2y',
            field=models.CharField(blank=True, max_length=200, verbose_name='CVM2_2_CODE CAMERA VIDEO MULTIFONCTION V2'),
        ),
        migrations.AddField(
            model_name='corvetproduct',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
