# Generated by Django 3.2.7 on 2021-12-14 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0028_alter_corvetchoices_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorvetOption',
            fields=[
                ('corvet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='opts', serialize=False, to='psa.corvet')),
                ('filter', models.CharField(blank=True, max_length=100, verbose_name='filtre')),
                ('update', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Options CORVET',
                'ordering': ['corvet'],
            },
        ),
    ]
