# Generated by Django 3.2.7 on 2021-12-14 14:20

from django.db import migrations


def create_corvetoptions(apps, schema_editor):
    Corvet = apps.get_model('psa', 'Corvet')
    CorvetOption = apps.get_model('psa', 'CorvetOption')
    for corvet in Corvet.objects.all():
        CorvetOption.objects.create(corvet=corvet)


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0029_corvetoption'),
    ]

    operations = [
        migrations.RunPython(create_corvetoptions)
    ]
