# Generated by Django 3.2.7 on 2021-12-16 13:56

from django.db import migrations


def update_corvetoptions(apps, schema_editor):
    Corvet = apps.get_model('psa', 'Corvet')
    CorvetOption = apps.get_model('psa', 'CorvetOption')
    for corvet in Corvet.objects.filter(prods__update=True):
        CorvetOption.objects.update_or_create(corvet=corvet, defaults={'update': True})


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0030_auto_20211214_1520'),
    ]

    operations = [
        migrations.RunPython(update_corvetoptions)
    ]
