# Generated by Django 3.2.7 on 2021-12-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0031_auto_20211216_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corvetoption',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='corvetproduct',
            name='update',
        ),
        migrations.AddField(
            model_name='corvetoption',
            name='tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='tag'),
        ),
    ]
