# Generated by Django 3.2.7 on 2021-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0032_auto_20211216_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecu',
            name='xelon_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='modèle Xelon'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='xelon_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='modèle Xelon'),
        ),
        migrations.AlterField(
            model_name='ecu',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='nom du modèle'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='name',
            field=models.CharField(blank=True, choices=[('RD3', 'RD3'), ('RD45', 'RD45'), ('RD5', 'RD5'), ('RDE', 'RDE'), ('RT3', 'RT3'), ('RT4', 'RT4'), ('RT5', 'RT5'), ('RT6', 'RT6 / RNEG2'), ('RT6v2', 'RT6v2 / RNEG2'), ('SMEG', 'SMEG'), ('SMEGP', 'SMEG+ / SMEG+ IV1'), ('SMEGP2', 'SMEG+ IV2'), ('NG4', 'NG4'), ('RNEG', 'RNEG'), ('RCC', 'RCC'), ('NAC1', 'NAC wave1'), ('NAC2', 'NAC wave2'), ('NAC3', 'NAC wave3'), ('NAC4', 'NAC wave4')], max_length=20, verbose_name='modèle'),
        ),
    ]
