# Generated by Django 3.2.11 on 2022-01-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0034_auto_20220119_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multimedia',
            options={'ordering': ['comp_ref'], 'verbose_name': 'Données Multimédia'},
        ),
        migrations.RenameField(
            model_name='multimedia',
            old_name='hw_reference',
            new_name='comp_ref',
        ),
        migrations.RenameField(
            model_name='multimedia',
            old_name='hw_type',
            new_name='mat_ref',
        ),
        migrations.AddField(
            model_name='multimedia',
            name='emmc',
            field=models.CharField(blank=True, max_length=100, verbose_name='eMMC'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='flash_nand',
            field=models.CharField(blank=True, max_length=100, verbose_name='flashNAND'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='flash_nor',
            field=models.CharField(blank=True, max_length=100, verbose_name='flashNOR'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='level',
            field=models.CharField(blank=True, max_length=100, verbose_name='niveau'),
        ),
    ]
