# Generated by Django 3.2.11 on 2022-01-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0035_auto_20220128_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='comp_ref',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='réf. comp. matériel'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='mat_ref',
            field=models.CharField(blank=True, max_length=10, verbose_name='réf. matériel'),
        ),
    ]
