# Generated by Django 3.2.12 on 2022-02-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0036_auto_20220128_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecu',
            name='label_ref',
            field=models.CharField(blank=True, max_length=10, verbose_name='réf. étiquette'),
        ),
    ]
