# Generated by Django 3.2.12 on 2022-03-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0037_ecu_label_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='pr_reference',
            field=models.CharField(blank=True, max_length=10, verbose_name='référence PR'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='type',
            field=models.CharField(choices=[('94B', 'BSI SOFT - Boitier Servitude Intelligent'), ('94A', 'CMM SOFT - Calculateur Moteur Multifonction'), ('94F', 'RADIO SOFT - Recepteur Radio'), ('94K', 'CMB SOFT - Combine Planche de Bord'), ('94L', 'EMF SOFT - Ecran Multifonctions'), ('94X', 'BTEL SOFT - Boitier Telematique'), ('96B', 'BSM SOFT - Boitier Servitude Moteur'), ('99H', 'MDS SOFT - Module de service telematique'), ('92Y', 'CVM2_2_ SOFT - CAMERA VIDEO MULTIFONCTION V2'), ('99K', 'ARTIV SOFT - Boitier Aide au Respect du Temps Inter Vehicule'), ('92E', 'AVM - SOFT - AIDE VISUELLE A LA MANŒUVRE'), ('96L', 'DAE SOFT - Direction Assistee Electrique')], max_length=3, verbose_name='type'),
        ),
    ]
