# Generated by Django 3.2.12 on 2022-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0038_auto_20220322_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecu',
            name='relation_by_name',
            field=models.BooleanField(default=False, verbose_name='relation par nom'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='relation_by_name',
            field=models.BooleanField(default=False, verbose_name='relation par nom'),
        ),
    ]
