# Generated by Django 3.2.13 on 2022-06-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0040_alter_multimedia_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorvetAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_1', models.CharField(max_length=100, verbose_name='cle1')),
                ('key_2', models.CharField(max_length=100, verbose_name='cle2')),
                ('label', models.CharField(max_length=500, verbose_name='libellé')),
                ('col_ext', models.CharField(max_length=10, verbose_name='colext')),
            ],
            options={
                'verbose_name': 'Attributs CORVET',
                'ordering': ['id'],
            },
        ),
    ]
