# Generated by Django 3.2.13 on 2022-08-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0041_corvetattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='ecu_type',
            field=models.CharField(choices=[('NAC_EUR_WAVE2', 'NAC_EUR_WAVE2'), ('NAC_EUR_WAVE1', 'NAC_EUR_WAVE1'), ('NAC_EUR_WAVE3', 'NAC_EUR_WAVE3'), ('NAC_EUR_WAVE4', 'NAV_EUR_WAVE4'), ('RCC_EU_W2', 'RCC_EU_W2'), ('RCC_EU_W3_ECO', 'RCC_EU_W3_ECO')], max_length=50, verbose_name='EcuType'),
        ),
    ]
