version: 2.1
orbs:
  python: circleci/python@2.0.3
  browser-tools: circleci/browser-tools@1.2.5
jobs: # A basic unit of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    # directory where steps are run
    working_directory: ~/circleci-csd-dashboard
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: cimg/python:3.8.13
      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      - image: cimg/postgres:9.6.24
        environment: # environment variables for the Postgres container.
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
      - image: cimg/redis:5.0.14
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - python/install-packages:
          args: "--dev"
          pkg-manager: pipenv
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - run:
          name: Run pipenv graph
          command: |
            pipenv graph
      - run:
          name: Run flake8
          command: |
            pipenv run flake8
      - run:
          name: Run Celery
          command: |
            pipenv run celery -A sbadmin purge -f
            pipenv run celery -A sbadmin worker --beat --scheduler django --loglevel=info
      - run:
          name: Run tests django
          environment:
            USER_CORVET: test
            PWD_CORVET: test
            DJANGO_SETTINGS_MODULE: sbadmin.settings.circleci
          command: |
            mkdir -m 0755 -p ~/Documents/CSD_DATABASE/EXTS/
            chown -R $USER:$USER ~/Documents/CSD_DATABASE/EXTS/
            pipenv run ./manage.py collectstatic --noinput
            pipenv run coverage run --source="." manage.py test -v 2
            pipenv run coverage report
