# Generated by Django 3.2.16 on 2023-02-08 13:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='code document')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='service')),
                ('nature', models.CharField(blank=True, max_length=1000, verbose_name='nature du document')),
                ('object', models.TextField(blank=True, verbose_name='object du documnet')),
                ('supplier', models.CharField(blank=True, max_length=500, verbose_name='fournisseur')),
                ('site', models.CharField(blank=True, max_length=100, verbose_name='site')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='contrat actif')),
                ('renew_date', models.DateField(blank=True, null=True, verbose_name='date prévenance')),
            ],
            options={
                'verbose_name': 'Contrat',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShowCollapse',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('general', models.BooleanField(default=False, verbose_name='informations générales')),
                ('motor', models.BooleanField(default=False, verbose_name='alimentation moteur')),
                ('axle', models.BooleanField(default=False, verbose_name='suspension direction freinage')),
                ('body', models.BooleanField(default=False, verbose_name='carrosserie équipements')),
                ('interior', models.BooleanField(default=False, verbose_name='equipements intérieur')),
                ('electric', models.BooleanField(default=False, verbose_name='électricité')),
                ('diverse', models.BooleanField(default=False, verbose_name='divers')),
            ],
            options={
                'verbose_name': 'Affichage detail',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('job_title', models.CharField(blank=True, max_length=500, verbose_name='intitulé de poste')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='service')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('url', models.URLField(verbose_name='lien web')),
                ('type', models.CharField(choices=[('PSA', 'PSA'), ('OPEL', 'OPEL'), ('FORD', 'FORD'), ('RENAULT', 'RENAULT'), ('CLARION', 'CLARION'), ('VAG', 'VAG'), ('PARTS_SUPPLIERS', 'PARTS_SUPPLIERS'), ('AUTRES', 'AUTRES')], max_length=50, verbose_name='type')),
                ('description', models.TextField(max_length=2000, verbose_name='description')),
                ('thumbnail', models.ImageField(default='no-img_160x120.png', upload_to='link_thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(max_length=5000, verbose_name='description')),
                ('objective', models.TextField(blank=True, max_length=1000, verbose_name='objectif')),
                ('status', models.CharField(choices=[('En Attente', 'En Attente'), ('En Cours', 'En Cours'), ('Terminée', 'Terminée'), ('Abandonnée', 'Abandonnée')], default='En Attente', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créer le')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='suggests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boite à idée',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('overview', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
