# Generated by Django 2.2.2 on 2019-07-02 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_csdsoftware'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csdsoftware',
            old_name='version',
            new_name='new_version',
        ),
        migrations.AddField(
            model_name='csdsoftware',
            name='old_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='csdsoftware',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='csdsoftware',
            name='status',
            field=models.CharField(choices=[('TEST', 'En test'), ('VALID', 'Validé'), ('ABANDONED', 'Abandonné')], max_length=50),
        ),
    ]
