# Generated by Django 3.0.3 on 2020-03-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200221_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsdSoftware',
        ),
    ]
