# Generated by Django 3.0.9 on 2020-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_csdsoftware'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('url', models.URLField(verbose_name='lien web')),
                ('type', models.CharField(choices=[('PSA', 'PSA'), ('OPEL', 'OPEL'), ('FORD', 'FORD'), ('RENAULT', 'RENAULT'), ('CLARION', 'CLARION'), ('AUTRES', 'AUTRES')], max_length=50, verbose_name='type')),
                ('description', models.TextField(max_length=2000, verbose_name='description')),
                ('thumbnail', models.ImageField(default='no-img_160x120.png', upload_to='link_thumbnail')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titre'),
        ),
    ]
