# Generated by Django 3.1.2 on 2020-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200827_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblink',
            name='type',
            field=models.CharField(choices=[('PSA', 'PSA'), ('OPEL', 'OPEL'), ('FORD', 'FORD'), ('RENAULT', 'RENAULT'), ('CLARION', 'CLARION'), ('VAG', 'VAG'), ('AUTRES', 'AUTRES')], max_length=50, verbose_name='type'),
        ),
    ]
