# Generated by Django 3.1.4 on 2021-02-03 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_auto_20201221_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCollapse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.BooleanField(default=False, verbose_name='informations générales')),
                ('motor', models.BooleanField(default=False, verbose_name='alimentation moteur')),
                ('interior', models.BooleanField(default=False, verbose_name='equipements intérieur')),
                ('diverse', models.BooleanField(default=False, verbose_name='divers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
