# Generated by Django 3.1.6 on 2021-02-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_showcollapse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcollapse',
            options={'verbose_name': 'Affichage detail'},
        ),
    ]
