# Generated by Django 3.2.4 on 2021-06-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210205_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcollapse',
            name='axle',
            field=models.BooleanField(default=False, verbose_name='suspension direction freinage'),
        ),
        migrations.AddField(
            model_name='showcollapse',
            name='body',
            field=models.BooleanField(default=False, verbose_name='carrosserie équipements'),
        ),
        migrations.AddField(
            model_name='showcollapse',
            name='electric',
            field=models.BooleanField(default=False, verbose_name='électricité'),
        ),
    ]
