# Generated by Django 3.2.13 on 2022-05-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20220509_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='code document')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='service')),
                ('nature', models.CharField(blank=True, max_length=1000, verbose_name='nature du document')),
                ('object', models.TextField(blank=True, verbose_name='object du documnet')),
                ('supplier', models.CharField(blank=True, max_length=500, verbose_name='fournisseur')),
                ('site', models.CharField(blank=True, max_length=100, verbose_name='site')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='contrat actif')),
                ('renew_date', models.DateField(blank=True, null=True, verbose_name='date prévenance')),
            ],
            options={
                'verbose_name': 'Contrat',
                'ordering': ['id'],
            },
        ),
    ]
