# Generated by Django 3.2.15 on 2022-10-18 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(max_length=5000, verbose_name='description')),
                ('objective', models.TextField(blank=True, max_length=1000, verbose_name='objectif')),
                ('status', models.CharField(choices=[('En Attente', 'En Attente'), ('En Cours', 'En Cours'), ('Terminée', 'Terminée'), ('Abandonnée', 'Abandonnée')], default='En Attente', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créer le')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='suggests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boite à idée',
                'ordering': ['-created_at'],
            },
        ),
    ]
