# Generated by Django 2.2.1 on 2019-05-14 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xelon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_dossier', models.CharField(max_length=10, unique=True)),
                ('vin', models.CharField(max_length=17)),
                ('modele_produit', models.CharField(max_length=50)),
                ('modele_vehicule', models.CharField(max_length=50)),
                ('reparer', models.BooleanField(default=False)),
                ('ajouter_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('cloture_le', models.DateTimeField(null=True)),
            ],
        ),
    ]
