# Generated by Django 2.2.1 on 2019-05-14 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xelon',
            name='ajouter_le',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='cloture_le',
            field=models.DateField(null=True),
        ),
    ]
