# Generated by Django 2.2.2 on 2019-06-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xelon',
            name='libelle_de_la_fiche_cas',
            field=models.CharField(max_length=5000, null=True, verbose_name='libellé de la fiche cas'),
        ),
    ]
