# Generated by Django 2.2.1 on 2019-05-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0002_auto_20190514_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorvetBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('data', models.CharField(max_length=5000)),
            ],
        ),
    ]
