# Generated by Django 2.2.2 on 2019-06-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0002_auto_20190613_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='xelon',
            name='delai_en_jours_calendaires',
            field=models.IntegerField(null=True, verbose_name='délai en jours calendaires'),
        ),
        migrations.AddField(
            model_name='xelon',
            name='delai_en_jours_ouvres',
            field=models.IntegerField(null=True, verbose_name='délai en jours ouvrés'),
        ),
        migrations.AddField(
            model_name='xelon',
            name='famille_client',
            field=models.CharField(max_length=5000, null=True, verbose_name='famille Client'),
        ),
        migrations.AddField(
            model_name='xelon',
            name='famille_produit',
            field=models.CharField(max_length=100, null=True, verbose_name='famille produit'),
        ),
    ]
