# Generated by Django 2.2.2 on 2019-06-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0003_auto_20190625_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xelon',
            name='commentaire_action',
            field=models.CharField(default='', max_length=5000, verbose_name='commentaire action'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='commentaire_de_la_fr',
            field=models.CharField(default='', max_length=5000, verbose_name='commentaire de la FR'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='commentaire_sav_admin',
            field=models.CharField(default='', max_length=5000, verbose_name='commentaire SAV Admin'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='date_de_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de clôture'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='famille_client',
            field=models.CharField(default='', max_length=5000, verbose_name='famille Client'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='famille_produit',
            field=models.CharField(default='', max_length=100, verbose_name='famille produit'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='libelle_de_la_fiche_cas',
            field=models.CharField(default='', max_length=5000, verbose_name='libellé de la fiche cas'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='lieu_de_stockage',
            field=models.CharField(default='', max_length=50, verbose_name='lieu de stockage'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='nom_technicien',
            field=models.CharField(default='', max_length=50, verbose_name='nom technicien'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='type_de_cloture',
            field=models.CharField(default='', max_length=50, verbose_name='type de clôture'),
        ),
    ]
