# Generated by Django 2.2.1 on 2019-05-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0003_corvetbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corvetbackup',
            name='vin',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
