# Generated by Django 2.2.2 on 2019-06-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0004_auto_20190625_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xelon',
            old_name='delai_en_jours_calendaires',
            new_name='delai_au_en_jours_calendaires',
        ),
        migrations.RenameField(
            model_name='xelon',
            old_name='delai_en_jours_ouvres',
            new_name='delai_au_en_jours_ouvres',
        ),
    ]
