# Generated by Django 2.2.1 on 2019-05-21 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0004_auto_20190516_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corvetbackup',
            name='data',
            field=models.CharField(max_length=5000, verbose_name='liste des données Corvet'),
        ),
        migrations.AlterField(
            model_name='corvetbackup',
            name='vin',
            field=models.CharField(max_length=17, unique=True, verbose_name='V.I.N.'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='ajouter_le',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='ajouté le'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='cloture_le',
            field=models.DateField(null=True, verbose_name='clôturé le'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='modele_produit',
            field=models.CharField(max_length=50, verbose_name='modèle produit'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='modele_vehicule',
            field=models.CharField(max_length=50, verbose_name='modèle véhicule'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='numero_de_dossier',
            field=models.CharField(max_length=10, unique=True, verbose_name='numéro de dossier'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='reparer',
            field=models.BooleanField(default=False, verbose_name='réparé'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='vin',
            field=models.CharField(max_length=17, verbose_name='V.I.N.'),
        ),
    ]
