# Generated by Django 3.2.25 on 2024-06-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0005_alter_productcategory_corvet_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xelon',
            options={'ordering': ['numero_de_dossier'], 'permissions': [('change_product', 'Can change product'), ('email_product', 'Can send email product'), ('change_vin', 'Can change vin'), ('email_vin', 'Can send email vin'), ('email_admin', 'Can send email admin'), ('active_xelon', 'Can active xelon'), ('change_sn', 'Can change Serial Number')], 'verbose_name': 'dossier Xelon'},
        ),
        migrations.AddField(
            model_name='xelon',
            name='new_sn',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nouveau S/N'),
        ),
    ]
