# Generated by Django 2.2.4 on 2019-08-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0005_auto_20190627_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corvet',
            name='donnee_date_debut_garantie',
            field=models.CharField(max_length=200, null=True, verbose_name='Date début garantie'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='donnee_date_entree_montage',
            field=models.CharField(max_length=200, null=True, verbose_name='Date entrée montage'),
        ),
    ]
