# Generated by Django 2.2.1 on 2019-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0006_corvet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dat',
            field=models.CharField(max_length=200, null=True, verbose_name='ANTENNE'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dcx',
            field=models.CharField(max_length=200, null=True, verbose_name='COTE  CONDUITE/POSTE CONDUITE'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_ddo',
            field=models.CharField(max_length=200, null=True, verbose_name='KIT TELEPHONE MAIN LIBRE'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dhb',
            field=models.CharField(max_length=200, null=True, verbose_name='HAUT PARLEUR'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dhg',
            field=models.CharField(max_length=200, null=True, verbose_name='COMMANDE AUTO-RADIO'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_djq',
            field=models.CharField(max_length=200, null=True, verbose_name='COMPACT DISQUE'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_djy',
            field=models.CharField(max_length=200, null=True, verbose_name='SYSTEME NAVIGATION'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dkx',
            field=models.CharField(max_length=200, null=True, verbose_name='CARTOGRAPHIE POUR NAVIGATION'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dlx',
            field=models.CharField(max_length=200, null=True, verbose_name='AFFICHEUR AV'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_doi',
            field=models.CharField(max_length=200, null=True, verbose_name='RECEPTION RADIO AMELIOREE'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dqm',
            field=models.CharField(max_length=200, null=True, verbose_name='TYPAGE GMP'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dqs',
            field=models.CharField(max_length=200, null=True, verbose_name='WIFI'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_drt',
            field=models.CharField(max_length=200, null=True, verbose_name='REGULATION CLIMAT/TEMPERATURE'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dti',
            field=models.CharField(max_length=200, null=True, verbose_name='TUNER RADIO'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dun',
            field=models.CharField(max_length=200, null=True, verbose_name='AMPLI EQUALISEUR'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dwt',
            field=models.CharField(max_length=200, null=True, verbose_name='PACK PREEQUIP. RADIO/COMMUNIC.'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dxj',
            field=models.CharField(max_length=200, null=True, verbose_name='ECRAN VIDEO AR'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dyb',
            field=models.CharField(max_length=200, null=True, verbose_name='VISION TETE HAUTE'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dym',
            field=models.CharField(max_length=200, null=True, verbose_name='PRISE AUXILIAIRE PACK AUDIO'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dyr',
            field=models.CharField(max_length=200, null=True, verbose_name='BOITIER TELEMATIQUE'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='attribut_dzv',
            field=models.CharField(max_length=200, null=True, verbose_name='AIDE A LA CONDUITE'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='donnee_genre_de_produit',
            field=models.CharField(max_length=200, null=True, verbose_name='GENRE_DE_PRODUIT'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_14b',
            field=models.CharField(max_length=200, null=True, verbose_name='BSI HARD - Boitier Servitude Intelligent'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_14f',
            field=models.CharField(max_length=200, null=True, verbose_name='RADIO HARD - Recepteur Radio'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_14k',
            field=models.CharField(max_length=200, null=True, verbose_name='CMB HARD - Combine Planche de Bord'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_14r',
            field=models.CharField(max_length=200, null=True, verbose_name='AAS HARD - Aide Au Stationnement'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_14x',
            field=models.CharField(max_length=200, null=True, verbose_name='BTEL HARD - Boitier Telematique (radio telephone)'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_19h',
            field=models.CharField(max_length=200, null=True, verbose_name='MDS HARD - Module de service telematique'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_19z',
            field=models.CharField(max_length=200, null=True, verbose_name='FMUX_HARD - FAÇADE MULTIPLEXÉ'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_34a',
            field=models.CharField(max_length=200, null=True, verbose_name='CMM SOFT LIVRE - Calculateur Moteur Multifonction'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_84a',
            field=models.CharField(max_length=200, null=True, verbose_name='CMM DOTE - Calculateur Moteur Multifonction'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_84b',
            field=models.CharField(max_length=200, null=True, verbose_name='BSI DOTE - Boitier Servitude Intelligent'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_84f',
            field=models.CharField(max_length=200, null=True, verbose_name='RADIO DOTE - Recepteur Radio'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_84l',
            field=models.CharField(max_length=200, null=True, verbose_name='EMF DOTE - Ecran Multifonctions'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_84x',
            field=models.CharField(max_length=200, null=True, verbose_name='BTEL DOTE - Boitier Telematique (radio telephone)'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_89h',
            field=models.CharField(max_length=200, null=True, verbose_name='MDS DOTE - Module de service telematique'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_94a',
            field=models.CharField(max_length=200, null=True, verbose_name='CMM SOFT - Calculateur Moteur Multifonction'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_94b',
            field=models.CharField(max_length=200, null=True, verbose_name='BSI SOFT - Boitier Servitude Intelligent'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_94f',
            field=models.CharField(max_length=200, null=True, verbose_name='RADIO SOFT - Recepteur Radio'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_94l',
            field=models.CharField(max_length=200, null=True, verbose_name='EMF SOFT - Ecran Multifonctions'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_94x',
            field=models.CharField(max_length=200, null=True, verbose_name='BTEL SOFT - Boitier Telematique (radio telephone)'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_99h',
            field=models.CharField(max_length=200, null=True, verbose_name='MDS SOFT - Module de service telematique'),
        ),
        migrations.AlterField(
            model_name='corvet',
            name='electronique_p4a',
            field=models.CharField(max_length=200, null=True, verbose_name='CMM EOBD - Calculateur Moteur Multifonction'),
        ),
    ]
