# Generated by Django 3.2.25 on 2024-06-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0006_auto_20240606_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xelon',
            old_name='new_sn',
            new_name='swap_sn',
        ),
    ]
