# Generated by Django 2.2.4 on 2019-08-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0006_auto_20190825_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xelon',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='V.I.N.'),
        ),
    ]
