# Generated by Django 2.2.4 on 2019-08-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0007_auto_20190825_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xelon',
            name='modele_produit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='modèle produit'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='modele_vehicule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='modèle véhicule'),
        ),
    ]
