# Generated by Django 2.2.1 on 2019-05-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0007_auto_20190521_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvet',
            name='xelons',
            field=models.ManyToManyField(to='squalaetp.Xelon'),
        ),
    ]
