# Generated by Django 3.2.25 on 2024-06-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0007_rename_new_sn_xelon_swap_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='xelon',
            name='swap_prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squalaetp.productcode'),
        ),
    ]
