# Generated by Django 2.2.4 on 2019-08-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0008_auto_20190828_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xelon',
            name='commentaire_action',
            field=models.CharField(blank=True, max_length=5000, verbose_name='commentaire action'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='commentaire_de_la_fr',
            field=models.CharField(blank=True, max_length=5000, verbose_name='commentaire de la FR'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='commentaire_sav_admin',
            field=models.CharField(blank=True, max_length=5000, verbose_name='commentaire SAV Admin'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='famille_client',
            field=models.CharField(blank=True, max_length=5000, verbose_name='famille Client'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='famille_produit',
            field=models.CharField(blank=True, max_length=100, verbose_name='famille produit'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='libelle_de_la_fiche_cas',
            field=models.CharField(blank=True, max_length=5000, verbose_name='libellé de la fiche cas'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='lieu_de_stockage',
            field=models.CharField(blank=True, max_length=50, verbose_name='lieu de stockage'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='modele_produit',
            field=models.CharField(blank=True, max_length=50, verbose_name='modèle produit'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='modele_vehicule',
            field=models.CharField(blank=True, max_length=50, verbose_name='modèle véhicule'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='nom_technicien',
            field=models.CharField(blank=True, max_length=50, verbose_name='nom technicien'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='type_de_cloture',
            field=models.CharField(blank=True, max_length=50, verbose_name='type de clôture'),
        ),
    ]
