# Generated by Django 3.2.25 on 2024-07-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0008_xelon_swap_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xelon',
            name='code_magasin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Code Magasin'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='code_zone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Code Zone'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='famille_produit',
            field=models.CharField(blank=True, max_length=200, verbose_name='famille produit'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='ilot',
            field=models.CharField(blank=True, max_length=200, verbose_name='ilot'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='lieu_de_stockage',
            field=models.CharField(blank=True, max_length=200, verbose_name='lieu de stockage'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='modele_produit',
            field=models.CharField(blank=True, max_length=200, verbose_name='modèle produit'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='modele_vehicule',
            field=models.CharField(blank=True, max_length=200, verbose_name='modèle véhicule'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='nom_technicien',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom technicien'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='type_de_cloture',
            field=models.CharField(blank=True, max_length=200, verbose_name='type de clôture'),
        ),
    ]
