# Generated by Django 2.2.1 on 2019-05-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0008_corvet_xelons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corvet',
            name='xelons',
            field=models.ManyToManyField(blank=True, related_name='corvet', to='squalaetp.Xelon'),
        ),
    ]
