# Generated by Django 2.2.4 on 2019-08-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0010_xelon_ilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xelon',
            name='vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='V.I.N.'),
        ),
    ]
