# Generated by Django 2.2.4 on 2019-08-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0011_auto_20190829_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xelon',
            name='date_retour',
            field=models.DateField(blank=True, null=True, verbose_name='date retour'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='delai_au_en_jours_calendaires',
            field=models.IntegerField(blank=True, null=True, verbose_name='délai en jours calendaires'),
        ),
        migrations.AlterField(
            model_name='xelon',
            name='delai_au_en_jours_ouvres',
            field=models.IntegerField(blank=True, null=True, verbose_name='délai en jours ouvrés'),
        ),
    ]
