# Generated by Django 2.2.5 on 2019-10-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0012_auto_20190829_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corvet',
            options={'ordering': ['vin'], 'verbose_name': 'données CORVET'},
        ),
        migrations.AlterModelOptions(
            name='xelon',
            options={'ordering': ['numero_de_dossier'], 'verbose_name': 'dossier Xelon'},
        ),
    ]
