# Generated by Django 2.2.6 on 2019-11-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0013_auto_20191004_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvet',
            name='electronique_16p',
            field=models.CharField(blank=True, max_length=200, verbose_name='HDC HARD - Haut de Colonne de Direction (COM200x)'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_46p',
            field=models.CharField(blank=True, max_length=200, verbose_name='HDC FOURN.NO.SERIE - Haut de Colonne de Direction (COM200x)'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_56p',
            field=models.CharField(blank=True, max_length=200, verbose_name='HDC FOURN.DATE.FAB - Haut de Colonne de Direction (COM200x)'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_66p',
            field=models.CharField(blank=True, max_length=200, verbose_name='HDC FOURN.CODE - Haut de Colonne de Direction (COM200x)'),
        ),
    ]
