# Generated by Django 3.0.4 on 2020-05-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0016_auto_20200113_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvet',
            name='electronique_16b',
            field=models.CharField(blank=True, max_length=200, verbose_name='BSM HARD - Boitier Servitude Moteur'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_46b',
            field=models.CharField(blank=True, max_length=200, verbose_name='BSM FOURN.NO.SERIE - Boitier Servitude Moteur'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_56b',
            field=models.CharField(blank=True, max_length=200, verbose_name='BSM FOURN.DATE.FAB - Boitier Servitude Moteur'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_66b',
            field=models.CharField(blank=True, max_length=200, verbose_name='BSM FOURN.CODE - Boitier Servitude Moteur'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_86b',
            field=models.CharField(blank=True, max_length=200, verbose_name='BSM DOTE - Boitier Servitude Moteur'),
        ),
        migrations.AddField(
            model_name='corvet',
            name='electronique_96b',
            field=models.CharField(blank=True, max_length=200, verbose_name='BSM SOFT - Boitier Servitude Moteur'),
        ),
    ]
