# Generated by Django 3.1.1 on 2020-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0018_productcode_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code_emplacement',
            field=models.CharField(blank=True, max_length=50, verbose_name='code Emplacement'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code_magasin',
            field=models.CharField(blank=True, max_length=50, verbose_name='code Magasin'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code_zone',
            field=models.CharField(blank=True, max_length=50, verbose_name='code Zone'),
        ),
    ]
