# Generated by Django 3.1.2 on 2020-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0019_auto_20200924_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date du jours')),
                ('products_to_repair', models.IntegerField(verbose_name='Produits à réparer')),
                ('late_products', models.IntegerField(verbose_name='Produits en retard')),
                ('express_products', models.IntegerField(verbose_name='Produits express')),
                ('output_products', models.IntegerField(verbose_name='Produits en sortie')),
                ('xelons', models.ManyToManyField(to='squalaetp.Xelon')),
            ],
        ),
    ]
