# Generated by Django 3.1.2 on 2020-11-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0020_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corvet',
            name='xelons',
        ),
    ]
