# Generated by Django 3.1.2 on 2020-11-18 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0004_calibration'),
        ('squalaetp', '0021_remove_corvet_xelons'),
    ]

    operations = [
        migrations.AddField(
            model_name='xelon',
            name='corvet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psa.corvet'),
        ),
    ]
