# Generated by Django 3.1.3 on 2020-12-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0023_xelon_vin_error'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corvet',
        ),
        migrations.DeleteModel(
            name='CorvetBackup',
        ),
    ]
