# Generated by Django 3.1.4 on 2020-12-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0025_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-modified_at'], 'verbose_name': 'Modification'},
        ),
    ]
