# Generated by Django 3.1.7 on 2021-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0026_auto_20201210_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='xelon',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Actif'),
        ),
    ]
