# Generated by Django 3.2 on 2021-05-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0028_rename_stock_sparepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(max_length=50, unique=True, verbose_name='modèle produit')),
                ('category', models.CharField(blank=True, choices=[('PSA', 'Produits PSA'), ('AUTRE', 'Autres produits'), ('CLARION', 'Clarion'), ('ETUDE', 'Etude'), ('CALCULATEUR', 'Calculateurs'), ('DEFAUT', 'Defaut')], max_length=50, verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie Produit',
                'ordering': ['product_model'],
            },
        ),
    ]
