# Generated by Django 3.2.6 on 2021-08-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0030_alter_xelon_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(choices=[('PSA', 'Produits PSA'), ('AUTRE', 'Autres produits'), ('CLARION', 'Clarion'), ('ETUDE', 'Etude'), ('CALCULATEUR', 'Calculateurs'), ('DEFAUT', 'Defaut')], default='DEFAUT', max_length=50, verbose_name='catégorie'),
        ),
    ]
