# Generated by Django 3.2.6 on 2021-08-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0031_alter_productcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='xelon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squalaetp.productcategory'),
        ),
    ]
