# Generated by Django 3.2.6 on 2021-08-25 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('squalaetp', '0032_xelon_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='niv_i_users',
            field=models.ManyToManyField(blank=True, related_name='niv_i_prods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='niv_l_users',
            field=models.ManyToManyField(blank=True, related_name='niv_l_prods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='niv_o_users',
            field=models.ManyToManyField(blank=True, related_name='niv_o_prods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='niv_u_users',
            field=models.ManyToManyField(blank=True, related_name='niv_u_prods', to=settings.AUTH_USER_MODEL),
        ),
    ]
