# Generated by Django 3.2.7 on 2021-11-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0026_alter_multimedia_name'),
        ('squalaetp', '0033_auto_20210825_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sivin',
            fields=[
                ('immat_siv', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Immatriculation SIV')),
                ('codif_vin', models.CharField(max_length=17, verbose_name='V.I.N.')),
                ('type_vin_cg', models.CharField(blank=True, max_length=6, verbose_name='Type VIN C.G. (VDS)')),
                ('type_var_vers_prf', models.CharField(blank=True, max_length=100, verbose_name='Type var vers prf')),
                ('n_serie', models.CharField(blank=True, max_length=8, verbose_name='Numéro de série (VIS)')),
                ('n_siren', models.CharField(blank=True, max_length=100, verbose_name='Numéro Siren')),
                ('date_1er_cir', models.CharField(blank=True, max_length=100, verbose_name='Date 1ère circulation')),
                ('date_dcg', models.CharField(blank=True, max_length=100, verbose_name='Date C.G.')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('marque_carros', models.CharField(blank=True, max_length=100, verbose_name='Marque carrosserie')),
                ('modele', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('modele_etude', models.CharField(blank=True, max_length=100, verbose_name='Modèle étude')),
                ('modele_prf', models.CharField(blank=True, max_length=100, verbose_name='Modèle préférence')),
                ('genre_v', models.CharField(blank=True, max_length=100, verbose_name='Genre véhicule')),
                ('genre_vcg', models.CharField(blank=True, max_length=100, verbose_name='Genre véhicule C.G.')),
                ('nb_portes', models.CharField(blank=True, max_length=100, verbose_name='Nombre portes')),
                ('nb_pl_ass', models.CharField(blank=True, max_length=100, verbose_name='Nombre de places assises')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Version')),
                ('energie', models.CharField(blank=True, max_length=100, verbose_name='Energie')),
                ('puis_ch', models.CharField(blank=True, max_length=100, verbose_name='Puissance chevau')),
                ('puis_fisc', models.CharField(blank=True, max_length=100, verbose_name='Puissance fiscale')),
                ('puis_kw', models.CharField(blank=True, max_length=100, verbose_name='Puissance Kw')),
                ('cons_exurb', models.CharField(blank=True, max_length=100, verbose_name='Consommation hors agglomération')),
                ('cons_mixte', models.CharField(blank=True, max_length=100, verbose_name='Consommation mixte')),
                ('cons_urb', models.CharField(blank=True, max_length=100, verbose_name='Consommation agglomération')),
                ('carrosserie', models.CharField(blank=True, max_length=100, verbose_name='Carrosserie')),
                ('carrosserie_cg', models.CharField(blank=True, max_length=100, verbose_name='Carrosserie C.G.')),
                ('couleur_vehic', models.CharField(blank=True, max_length=100, verbose_name='Couleur véhicule')),
                ('empat', models.CharField(blank=True, max_length=100, verbose_name='Empattement véhicule')),
                ('hauteur', models.CharField(blank=True, max_length=100, verbose_name='Hauteur')),
                ('largeur', models.CharField(blank=True, max_length=100, verbose_name='Largeur')),
                ('longueur', models.CharField(blank=True, max_length=100, verbose_name='Longueur')),
                ('poids_vide', models.CharField(blank=True, max_length=100, verbose_name='Poids à vide')),
                ('ptr', models.CharField(blank=True, max_length=100, verbose_name='PTR')),
                ('ptr_prf', models.CharField(blank=True, max_length=100, verbose_name='PTR Prf')),
                ('pneus', models.CharField(blank=True, max_length=100, verbose_name='Pneus')),
                ('code_moteur', models.CharField(blank=True, max_length=100, verbose_name='Code moteur')),
                ('mode_inject', models.CharField(blank=True, max_length=100, verbose_name="Mode d'injection")),
                ('cylindree', models.CharField(blank=True, max_length=100, verbose_name='Cylindrée')),
                ('nb_cylind', models.CharField(blank=True, max_length=100, verbose_name='Nombre cylindres')),
                ('nb_soupape', models.CharField(blank=True, max_length=100, verbose_name='Nombre soupapes')),
                ('turbo_compr', models.CharField(blank=True, max_length=100, verbose_name='Turbo compresseur')),
                ('co2', models.CharField(blank=True, max_length=100, verbose_name='Emission CO2')),
                ('depollution', models.CharField(blank=True, max_length=100, verbose_name='Dépollution')),
                ('tp_boit_vit', models.CharField(blank=True, max_length=100, verbose_name='Type de boîte de vitesse')),
                ('nb_vitesse', models.CharField(blank=True, max_length=100, verbose_name='Nombre de vitesses')),
                ('nb_volume', models.CharField(blank=True, max_length=100, verbose_name='Nombre de volume')),
                ('propulsion', models.CharField(blank=True, max_length=100, verbose_name='Type propulsion')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('prix_vehic', models.CharField(blank=True, max_length=100, verbose_name='Prix véhicule')),
                ('corvet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psa.corvet')),
            ],
            options={
                'verbose_name': 'Données SIVIN',
                'ordering': ['immat_siv'],
            },
        ),
    ]
