# Generated by Django 3.2.7 on 2021-12-22 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0032_auto_20211216_1459'),
        ('squalaetp', '0034_sivin'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='ecu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psa.ecu'),
        ),
        migrations.AddField(
            model_name='productcode',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psa.multimedia'),
        ),
    ]
