# Generated by Django 3.2.12 on 2022-04-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0038_alter_productcategory_corvet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='xelon',
            name='appairage',
            field=models.CharField(blank=True, max_length=50, verbose_name='APPAIRAGE'),
        ),
        migrations.AddField(
            model_name='xelon',
            name='telecodage',
            field=models.CharField(blank=True, max_length=50, verbose_name='TELECODAGE'),
        ),
    ]
