# Generated by Django 3.2.13 on 2022-05-03 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('squalaetp', '0039_auto_20220413_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='animator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animator_prods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='fa_users',
            field=models.ManyToManyField(blank=True, related_name='fa_prods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='fe_users',
            field=models.ManyToManyField(blank=True, related_name='fe_prods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='niv_t_users',
            field=models.ManyToManyField(blank=True, related_name='niv_t_prods', to=settings.AUTH_USER_MODEL),
        ),
    ]
