# Generated by Django 3.2.13 on 2022-05-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0040_auto_20220503_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xelon',
            options={'ordering': ['numero_de_dossier'], 'permissions': [('change_product', 'Can change product'), ('email_product', 'Can send email product'), ('change_vin', 'Can change vin'), ('email_vin', 'Can send email vin'), ('email_admin', 'Can send email admin'), ('active_xelon', 'Can active xelon')], 'verbose_name': 'dossier Xelon'},
        ),
        migrations.AddField(
            model_name='xelon',
            name='pays',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='xelon',
            name='rm',
            field=models.CharField(blank=True, max_length=50, verbose_name='RM'),
        ),
    ]
