# Generated by Django 3.2.12 on 2022-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0038_auto_20220322_1035'),
        ('squalaetp', '0041_auto_20220520_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcode',
            name='ecu',
        ),
        migrations.RemoveField(
            model_name='productcode',
            name='media',
        ),
        migrations.AddField(
            model_name='productcode',
            name='ecus',
            field=models.ManyToManyField(blank=True, related_name='parts', to='psa.Ecu'),
        ),
        migrations.AddField(
            model_name='productcode',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='parts', to='psa.Multimedia'),
        ),
    ]
