# Generated by Django 3.2.13 on 2022-06-21 10:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0040_alter_multimedia_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('squalaetp', '0042_auto_20220525_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='XelonTemporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_dossier', models.CharField(max_length=10, verbose_name='numéro de dossier')),
                ('vin', models.CharField(max_length=17, verbose_name='V.I.N.')),
                ('modele_produit', models.CharField(blank=True, max_length=50, verbose_name='modèle produit')),
                ('modele_vehicule', models.CharField(blank=True, max_length=50, verbose_name='modèle véhicule')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('end_date', models.DateField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 18, 9, 611526, tzinfo=utc), null=True, verbose_name='date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corvet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psa.corvet')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
