# Generated by Django 3.2.13 on 2022-06-28 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0043_xelontemporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xelontemporary',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 6, 48, 8, 906405, tzinfo=utc), null=True, verbose_name='date de fin'),
        ),
    ]
