# Generated by Django 3.2.15 on 2022-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0044_alter_xelontemporary_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='xelon',
            name='code_magasin',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code Magasin'),
        ),
        migrations.AddField(
            model_name='xelon',
            name='code_zone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code Zone'),
        ),
    ]
