# Generated by Django 3.2.15 on 2022-09-13 12:45

from django.db import migrations


def code_fields_update(apps, schema_editor):
    Xelon = apps.get_model('squalaetp', 'Xelon')
    for xelon in Xelon.objects.exclude(lieu_de_stockage=''):
        try:
            xelon.code_magasin, xelon.code_zone = xelon.lieu_de_stockage.split('/')
            xelon.save()
        except ValueError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0045_auto_20220913_1445'),
    ]

    operations = [
        migrations.RunPython(code_fields_update)
    ]
