# Generated by Django 3.2.16 on 2022-12-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squalaetp', '0046_auto_20220913_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='sivin',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, verbose_name='Latitude'),
        ),
    ]
