# Generated by Django 3.2.8 on 2022-01-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemRefBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reman_reference', models.CharField(max_length=10, unique=True, verbose_name='référence REMAN')),
                ('map_data', models.CharField(blank=True, max_length=100, verbose_name='map data')),
                ('oe_reference', models.CharField(blank=True, max_length=8, verbose_name='product part')),
                ('pf_code', models.CharField(blank=True, max_length=10, verbose_name='PF code')),
                ('asm', models.CharField(blank=True, max_length=12, verbose_name='ASM')),
                ('hw', models.CharField(blank=True, max_length=12, verbose_name='HW')),
            ],
        ),
    ]
