from django.db import models
from django.utils import timezone


class Xelon(models.Model):
    numero_de_dossier = models.CharField('numéro de dossier', max_length=10, unique=True)
    vin = models.CharField('V.I.N.', max_length=17)
    modele_produit = models.CharField('modèle produit', max_length=50)
    modele_vehicule = models.CharField('modèle véhicule', max_length=50)
    reparer = models.BooleanField('réparé', default=False)
    ajouter_le = models.DateField('ajouté le', default=timezone.now)
    cloture_le =models.DateField('clôturé le', null=True)

    def __str__(self):
        return "{} - {} - {} - {}".format(self.numero_de_dossier, self.vin, self.modele_produit, self.modele_vehicule)


class CorvetBackup(models.Model):
    vin = models.CharField('V.I.N.', max_length=17, unique=True)
    data = models.CharField('liste des données Corvet', max_length=5000)

    def __str__(self):
        return self.vin


class Corvet(models.Model):
    vin = models.CharField('V.I.N.', max_length=17, primary_key=True)
    donnee_date_debut_garantie = models.CharField('Date d?but garantie', max_length=200, null=True)
    donnee_date_entree_montage = models.CharField('Date entr?e montage', max_length=200, null=True)
    donnee_ligne_de_produit = models.CharField('LIGNE_DE_PRODUIT', max_length=200, null=True)
    donnee_marque_commerciale = models.CharField('MARQUE_COMMERCIALE', max_length=200, null=True)
    donnee_silhouette = models.CharField('SILHOUETTE', max_length=200, null=True)
    donnee_genre_de_produit = models.IntegerField('GENRE_DE_PRODUIT', null=True)
    attribut_ddo = models.IntegerField('KIT TELEPHONE MAIN LIBRE', null=True)
    attribut_dgm = models.CharField('COMBINE (CARACTERISTIQUES)', max_length=200, null=True)
    attribut_dhb = models.IntegerField('HAUT PARLEUR', null=True)
    attribut_dhg = models.IntegerField('COMMANDE AUTO-RADIO', null=True)
    attribut_djq = models.IntegerField('COMPACT DISQUE', null=True)
    attribut_djy = models.IntegerField('SYSTEME NAVIGATION', null=True)
    attribut_dkx = models.IntegerField('CARTOGRAPHIE POUR NAVIGATION', null=True)
    attribut_dlx = models.IntegerField('AFFICHEUR AV', null=True)
    attribut_doi = models.IntegerField('RECEPTION RADIO AMELIOREE', null=True)
    attribut_dqm = models.IntegerField('TYPAGE GMP', null=True)
    attribut_dqs = models.IntegerField('WIFI', null=True)
    attribut_drc = models.CharField('RECEPTEUR RADIO', max_length=200, null=True)
    attribut_drt = models.IntegerField('REGULATION CLIMAT/TEMPERATURE', null=True)
    attribut_dti = models.IntegerField('TUNER RADIO', null=True)
    attribut_dun = models.IntegerField('AMPLI EQUALISEUR', null=True)
    attribut_dwl = models.CharField('PACK RADIO/INFO/COMMUNICATION', max_length=200, null=True)
    attribut_dwt = models.IntegerField('PACK PREEQUIP. RADIO/COMMUNIC.', null=True)
    attribut_dxj = models.IntegerField('ECRAN VIDEO AR', null=True)
    attribut_dyb = models.IntegerField('VISION TETE HAUTE', null=True)
    attribut_dym = models.IntegerField('PRISE AUXILIAIRE PACK AUDIO', null=True)
    attribut_dyr = models.IntegerField('BOITIER TELEMATIQUE', null=True)
    attribut_dzv = models.IntegerField('AIDE A LA CONDUITE', null=True)
    attribut_gg8 = models.CharField('PAYS PROGRAMME (ICP)', max_length=200, null=True)
    electronique_14f = models.IntegerField('RADIO HARD - Recepteur Radio', null=True)
    electronique_14j = models.CharField('CLIM HARD - Climatisation', max_length=200, null=True)
    electronique_14k = models.IntegerField('CMB HARD - Combine Planche de Bord', null=True)
    electronique_14l = models.CharField('EMF HARD - Ecran Multifonctions', max_length=200, null=True)
    electronique_14r = models.IntegerField('AAS HARD - Aide Au Stationnement', null=True)
    electronique_14x = models.IntegerField('BTEL HARD - Boitier Telematique (radio telephone)', null=True)
    electronique_19z = models.IntegerField('FMUX_HARD - FAÇADE MULTIPLEXÉ', null=True)
    electronique_44f = models.CharField('RADIO FOURN.NO.SERIE - Recepteur Radio', max_length=200, null=True)
    electronique_44l = models.CharField('EMF FOURN.NO.SERIE - Ecran Multifonctions', max_length=200, null=True)
    electronique_44x = models.CharField('BTEL FOURN.NO.SERIE - Boitier Telematique (radio telephone)', max_length=200, null=True)
    electronique_54f = models.CharField('RADIO FOURN.DATE.FAB - Recepteur Radio', max_length=200, null=True)
    electronique_54k = models.CharField('CMB FOURN.DATE.FAB - Combine Planche de Bord', max_length=200, null=True)
    electronique_54l = models.CharField('EMF FOURN.DATE.FAB - Ecran Multifonctions', max_length=200, null=True)
    electronique_84f = models.IntegerField('RADIO DOTE - Recepteur Radio', null=True)
    electronique_84l = models.IntegerField('EMF DOTE - Ecran Multifonctions', null=True)
    electronique_84x = models.IntegerField('BTEL DOTE - Boitier Telematique (radio telephone)', null=True)
    electronique_94f = models.IntegerField('RADIO SOFT - Recepteur Radio', null=True)
    electronique_94l = models.IntegerField('EMF SOFT - Ecran Multifonctions', null=True)
    electronique_94x = models.IntegerField('BTEL SOFT - Boitier Telematique (radio telephone)', null=True)
    attribut_dat = models.IntegerField('ANTENNE', null=True)
    attribut_dcx = models.IntegerField('COTE  CONDUITE/POSTE CONDUITE', null=True)
    electronique_19h = models.IntegerField('MDS HARD - Module de service telematique', null=True)
    electronique_49h = models.CharField('MDS FOURN.NO.SERIE - Module de service telematique', max_length=200, null=True)
    electronique_64f = models.CharField('RADIO FOURN.CODE - Recepteur Radio', max_length=200, null=True)
    electronique_64x = models.CharField('BTEL FOURN.CODE - Boitier Telematique (radio telephone)', max_length=200, null=True)
    electronique_69h = models.CharField('MDS FOURN.CODE - Module de service telematique', max_length=200, null=True)
    electronique_89h = models.IntegerField('MDS DOTE - Module de service telematique', null=True)
    electronique_99h = models.IntegerField('MDS SOFT - Module de service telematique', null=True)
    electronique_14a = models.CharField('CMM HARD - Calculateur Moteur Multifonction', max_length=200, null=True)
    electronique_34a = models.IntegerField('CMM SOFT LIVRE - Calculateur Moteur Multifonction', null=True)
    electronique_44a = models.CharField('CMM FOURN.NO.SERIE - Calculateur Moteur Multifonction', max_length=200, null=True)
    electronique_54a = models.CharField('CMM FOURN.DATE.FAB - Calculateur Moteur Multifonction', max_length=200, null=True)
    electronique_64a = models.CharField('CMM FOURN.CODE - Calculateur Moteur Multifonction', max_length=200, null=True)
    electronique_84a = models.IntegerField('CMM DOTE - Calculateur Moteur Multifonction', null=True)
    electronique_94a = models.IntegerField('CMM SOFT - Calculateur Moteur Multifonction', null=True)
    electronique_p4a = models.IntegerField('CMM EOBD - Calculateur Moteur Multifonction', null=True)
    donnee_moteur = models.CharField('MOTEUR', max_length=200, null=True)
    donnee_transmission = models.CharField('TRANSMISSION', max_length=200, null=True)
    organes_10 = models.CharField('MOTEUR', max_length=200, null=True)
    electronique_14b = models.IntegerField('BSI HARD - Boitier Servitude Intelligent', null=True)
    organes_20 = models.CharField('BOITE DE VITESSES', max_length=200, null=True)
    electronique_44b = models.CharField('BSI FOURN.NO.SERIE - Boitier Servitude Intelligent', max_length=200, null=True)
    electronique_54b = models.CharField('BSI FOURN.DATE.FAB - Boitier Servitude Intelligent', max_length=200, null=True)
    electronique_64b = models.CharField('BSI FOURN.CODE - Boitier Servitude Intelligent', max_length=200, null=True)
    electronique_84b = models.IntegerField('BSI DOTE - Boitier Servitude Intelligent', null=True)
    electronique_94b = models.IntegerField('BSI SOFT - Boitier Servitude Intelligent', null=True)
