# Generated by Django 3.0.3 on 2020-03-01 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsdSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jig', models.CharField(max_length=100)),
                ('new_version', models.CharField(max_length=20)),
                ('old_version', models.CharField(blank=True, max_length=20, null=True)),
                ('link_download', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Validé', 'Validé'), ('En test', 'En test'), ('Etudes', 'Etudes'), ('Abandonné', 'Abandonné'), ('PDI Only', 'PDI Only')], max_length=50)),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
