# Generated by Django 3.2.18 on 2023-04-18 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suptechcategory',
            name='cc',
            field=models.TextField(default='test1@test.com; test2@test.com', max_length=5000, verbose_name='CC'),
        ),
        migrations.AddField(
            model_name='suptechcategory',
            name='to',
            field=models.TextField(default='test1@test.com; test2@test.com', max_length=5000, verbose_name='TO'),
        ),
        migrations.CreateModel(
            name='SuptechAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('added_at', models.DateTimeField(auto_now=True, verbose_name='ajouté le')),
                ('object_id', models.PositiveIntegerField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_added', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SupTech Action',
                'ordering': ['-added_at'],
            },
        ),
    ]
