# Generated by Django 3.0.4 on 2020-03-08 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0002_csdsoftware'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalChamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_mode', models.CharField(choices=[('FROID', 'FROID'), ('CHAUD', 'CHAUD')], max_length=20, verbose_name='mode de fonctionnement')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='heure de début')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
