# Generated by Django 3.2.19 on 2023-06-28 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0003_rename_suptechmessage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfotechMailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('cc_users', models.ManyToManyField(blank=True, related_name='cc_info_emails', to=settings.AUTH_USER_MODEL)),
                ('to_users', models.ManyToManyField(blank=True, related_name='to_info_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InfoTech Mailing List',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Infotech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='ITEM')),
                ('info', models.TextField(max_length=2000, verbose_name='INFO')),
                ('action', models.TextField(blank=True, max_length=2000, verbose_name='ACTION/RETOUR')),
                ('status', models.TextField(choices=[('En Cours', 'En Cours'), ('Cloturée', 'Cloturée')], default='En Cours', max_length=50, verbose_name='STATUT')),
                ('to', models.TextField(max_length=5000, verbose_name='TO')),
                ('cc', models.TextField(max_length=5000, verbose_name='CC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ajouté le')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='modifié le')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infotechs_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infotechs_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InfoTech',
                'ordering': ['pk'],
            },
        ),
    ]
