# Generated by Django 3.0.5 on 2020-05-13 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_thermalchamber'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='projet')),
                ('progress', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='avancée en %')),
            ],
        ),
    ]
