# Generated by Django 3.0.8 on 2020-07-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_etudeproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalchamber',
            name='xelon_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='N° Xelon'),
        ),
    ]
