# Generated by Django 3.2.22 on 2023-10-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_infotech_infotechmailinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaspiTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la machine')),
                ('type', models.CharField(choices=[('RASPEEDI', 'RASPEEDI'), ('AET', 'AET'), ('CANPI', 'CANPI')], max_length=50, verbose_name='type')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='heure de START')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='heure de FIN')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='durée en secondes')),
            ],
            options={
                'verbose_name': 'RasPi Time',
                'ordering': ['id'],
            },
        ),
    ]
