# Generated by Django 3.2.22 on 2023-10-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_raspitime'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspitime',
            name='xelon',
            field=models.CharField(blank=True, max_length=10, verbose_name='n° Xelon'),
        ),
    ]
