# Generated by Django 3.2.22 on 2023-11-10 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0006_raspitime_xelon'),
    ]

    operations = [
        migrations.AddField(
            model_name='suptechcategory',
            name='cc_users',
            field=models.ManyToManyField(blank=True, related_name='cc_sup_cats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suptechcategory',
            name='to_users',
            field=models.ManyToManyField(blank=True, related_name='to_sup_cats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suptechcategory',
            name='cc',
            field=models.TextField(blank=True, default='test1@test.com; test2@test.com', max_length=5000, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='suptechcategory',
            name='to',
            field=models.TextField(blank=True, default='test1@test.com; test2@test.com', max_length=5000, verbose_name='TO'),
        ),
        migrations.AlterField(
            model_name='suptechitem',
            name='cc_mailing_list',
            field=models.TextField(blank=True, default='test1@test.com; test2@test.com', max_length=5000, verbose_name="liste d'email CC"),
        ),
        migrations.AlterField(
            model_name='suptechitem',
            name='mailing_list',
            field=models.TextField(blank=True, default='test1@test.com; test2@test.com', max_length=5000, verbose_name="Liste d'email"),
        ),
    ]
