# Generated by Django 3.1.6 on 2021-02-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_thermalchamber_stop_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suptech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='DATE')),
                ('user', models.CharField(max_length=50, verbose_name='QUI')),
                ('xelon', models.CharField(blank=True, max_length=10, verbose_name='XELON')),
                ('item', models.CharField(max_length=200, verbose_name='ITEM')),
                ('time', models.CharField(max_length=50, verbose_name='TIME')),
                ('info', models.TextField(max_length=5000, verbose_name='INFO')),
                ('rmq', models.TextField(blank=True, max_length=5000, verbose_name='RMQ')),
                ('action', models.TextField(blank=True, max_length=5000, verbose_name='ACTION/RETOUR')),
            ],
            options={
                'verbose_name': 'Logs SupTech',
                'ordering': ['pk'],
            },
        ),
    ]
