# Generated by Django 3.1.7 on 2021-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_suptech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suptech',
            name='action',
            field=models.TextField(blank=True, max_length=2000, verbose_name='ACTION/RETOUR'),
        ),
        migrations.AlterField(
            model_name='suptech',
            name='info',
            field=models.TextField(max_length=2000, verbose_name='INFO'),
        ),
        migrations.AlterField(
            model_name='suptech',
            name='item',
            field=models.CharField(choices=[('Hot Line Tech', 'Hot Line Tech'), ('Support Admin', 'Support Admin'), ('R.M.', 'R.M.'), ('Temps Annexe', 'Temps Annexe'), ('Validation Tech', 'Validation Tech'), ('Retour Autotronik', 'Retour Autotronik'), ('Probleme process', 'Probleme process'), ('Informatique/Reseau', 'Informatique/Reseau'), ('Inter Maintenance(AF/YM)', 'Inter Maintenance(AF/YM)'), ('Autres... (Avec resumé)', 'Autres... (Avec resumé)')], max_length=100, verbose_name='ITEM'),
        ),
        migrations.AlterField(
            model_name='suptech',
            name='rmq',
            field=models.TextField(blank=True, max_length=2000, verbose_name='RMQ'),
        ),
        migrations.AlterField(
            model_name='suptech',
            name='time',
            field=models.CharField(max_length=10, verbose_name='TIME'),
        ),
    ]
