# Generated by Django 3.1.7 on 2021-03-14 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0007_suptech'),
    ]

    operations = [
        migrations.AddField(
            model_name='suptech',
            name='created_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='ajouté le'),
        ),
        migrations.AddField(
            model_name='suptech',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suptechs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suptech',
            name='modified_at',
            field=models.DateTimeField(null=True, verbose_name='modifié le'),
        ),
        migrations.AddField(
            model_name='suptech',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suptechs_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suptech',
            name='action',
            field=models.TextField(blank=True, max_length=2000, verbose_name='ACTION/RETOUR'),
        ),
        migrations.AlterField(
            model_name='suptech',
            name='info',
            field=models.TextField(max_length=2000, verbose_name='INFO'),
        ),
        migrations.AlterField(
            model_name='suptech',
            name='item',
            field=models.CharField(choices=[('Hot Line Tech', 'Hot Line Tech'), ('Support Admin', 'Support Admin'), ('R.M.', 'R.M.'), ('Temps Annexe', 'Temps Annexe'), ('Validation Tech', 'Validation Tech'), ('Retour Autotronik', 'Retour Autotronik'), ('Probleme process', 'Probleme process'), ('Informatique/Reseau', 'Informatique/Reseau'), ('Inter Maintenance(AF/YM)', 'Inter Maintenance(AF/YM)'), ('Autres... (Avec resumé)', 'Autres... (Avec resumé)')], max_length=100, verbose_name='ITEM'),
        ),
        migrations.AlterField(
            model_name='suptech',
            name='rmq',
            field=models.TextField(blank=True, max_length=2000, verbose_name='RMQ'),
        ),
        migrations.AlterField(
            model_name='suptech',
            name='time',
            field=models.CharField(max_length=10, verbose_name='TIME'),
        ),
    ]
