# Generated by Django 3.1.7 on 2021-03-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20210314_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suptech',
            name='item',
            field=models.CharField(max_length=100, verbose_name='ITEM'),
        ),
    ]
