# Generated by Django 3.2 on 2021-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_auto_20210506_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suptech',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='DATE LIMITE'),
        ),
    ]
