# Generated by Django 3.2.25 on 2024-08-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_suptech_days_late'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagxelon',
            name='calibre',
            field=models.BooleanField(choices=[(False, 'CAL software'), (True, 'Diagbox')], default=False, verbose_name='calibration'),
        ),
        migrations.AlterField(
            model_name='tagxelon',
            name='telecode',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='télécodage'),
        ),
    ]
