# Generated by Django 4.2.16 on 2024-10-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_auto_20240829_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgatime',
            options={'ordering': ['-id'], 'verbose_name': 'BGA Time'},
        ),
        migrations.AlterModelOptions(
            name='raspitime',
            options={'ordering': ['-id'], 'verbose_name': 'RasPi Time'},
        ),
        migrations.AddConstraint(
            model_name='bgatime',
            constraint=models.UniqueConstraint(fields=('name', 'date', 'start_time'), name='unique_bga_time'),
        ),
        migrations.AddConstraint(
            model_name='raspitime',
            constraint=models.UniqueConstraint(fields=('name', 'date', 'start_time'), name='unique_raspi_time'),
        ),
    ]
