# Generated by Django 3.2.3 on 2021-06-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_alter_suptech_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuptechItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('extra', models.BooleanField(default=False)),
                ('mailing_list', models.TextField(default='test1@test.com; test2@test.com', max_length=5000, verbose_name="Liste d'email")),
            ],
            options={
                'verbose_name': 'SupTech Item',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='suptech',
            options={'ordering': ['pk'], 'verbose_name': 'SupTech Log'},
        ),
        migrations.AlterField(
            model_name='suptech',
            name='item',
            field=models.CharField(max_length=200, verbose_name='ITEM'),
        ),
    ]
