# Generated by Django 3.2.4 on 2021-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_auto_20210601_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgaTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la machine')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='heure de START')),
                ('end_time', models.TimeField(null=True, verbose_name='heure de FIN')),
            ],
            options={
                'verbose_name': 'BGA Time',
                'ordering': ['date'],
            },
        ),
    ]
