# Generated by Django 3.2.4 on 2021-06-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_bgatime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgatime',
            options={'ordering': ['id'], 'verbose_name': 'BGA Time'},
        ),
        migrations.AddField(
            model_name='bgatime',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='durée en secondes'),
        ),
    ]
