# Generated by Django 3.2.4 on 2021-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_auto_20210615_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalChamberMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='heure de mesure')),
                ('value', models.IntegerField(verbose_name='valeur mesuré')),
                ('temp', models.CharField(max_length=20, verbose_name='température')),
            ],
            options={
                'verbose_name': 'Thermal Chamber Measure',
                'ordering': ['-datetime'],
            },
        ),
    ]
