# Generated by Django 3.2.8 on 2021-10-19 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0017_auto_20210922_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='suptechcategory',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suptechs_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
