# Generated by Django 3.2.12 on 2022-02-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_suptechcategory_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='suptechitem',
            name='cc_mailing_list',
            field=models.TextField(default='test1@test.com; test2@test.com', max_length=5000, verbose_name="liste d'email CC"),
        ),
    ]
