# Generated by Django 3.2.12 on 2022-04-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0019_suptechitem_cc_mailing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='suptech',
            name='is_48h',
            field=models.BooleanField(default=True, verbose_name='Traitement 48h'),
        ),
        migrations.AddField(
            model_name='suptechitem',
            name='is_48h',
            field=models.BooleanField(default=True, verbose_name='Traitement 48h'),
        ),
    ]
