# Generated by Django 3.2.13 on 2022-05-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0022_suptechfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagxelon',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tag Xelon Multi'},
        ),
        migrations.AddField(
            model_name='tagxelon',
            name='calibre',
            field=models.BooleanField(choices=[(False, 'CAL software'), (True, 'With Diagbox')], default=False, verbose_name='calibration'),
        ),
        migrations.AddField(
            model_name='tagxelon',
            name='telecode',
            field=models.BooleanField(choices=[(False, 'Non'), (True, 'Oui')], default=False, verbose_name='télécodage'),
        ),
    ]
