# Generated by Django 3.2.12 on 2022-05-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0023_auto_20220505_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagxelon',
            name='calibre',
            field=models.BooleanField(choices=[(False, 'Logiciel CAL'), (True, 'Diagbox')], default=False, verbose_name='calibration'),
        ),
    ]
