# Generated by Django 3.2.15 on 2022-10-06 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0024_alter_tagxelon_calibre'),
    ]

    operations = [
        migrations.AddField(
            model_name='suptechitem',
            name='cc_users',
            field=models.ManyToManyField(blank=True, related_name='cc_sup_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suptechitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='suptechitem',
            name='to_users',
            field=models.ManyToManyField(blank=True, related_name='to_sup_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
