# Generated by Django 3.2.15 on 2022-11-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0025_auto_20221006_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path', models.CharField(max_length=500, unique=True)),
                ('filename', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
