# Generated by Django 3.2.15 on 2022-11-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0026_configfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='content',
            field=models.TextField(verbose_name='contenu du fichier'),
        ),
        migrations.AlterField(
            model_name='configfile',
            name='filename',
            field=models.CharField(max_length=100, verbose_name='nom du fichier'),
        ),
        migrations.AlterField(
            model_name='configfile',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nom du logiciel'),
        ),
        migrations.AlterField(
            model_name='configfile',
            name='path',
            field=models.CharField(max_length=500, unique=True, verbose_name='chemin du fichier'),
        ),
    ]
