# Generated by Django 3.2.16 on 2022-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0027_auto_20221108_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='suptech',
            name='product',
            field=models.CharField(blank=True, max_length=200, verbose_name='PRODUCT'),
        ),
    ]
