# Generated by Django 3.2.18 on 2023-02-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Nom de l'outils")),
                ('url', models.CharField(max_length=500, verbose_name='Lien web')),
                ('status_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin page statut')),
                ('api_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin API')),
            ],
            options={
                'verbose_name': 'Statut Outil',
                'ordering': ['name'],
            },
        ),
    ]
