# Generated by Django 2.2.2 on 2019-06-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0003_addreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspeedi',
            name='carto',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='version cartographie'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='cd_version',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='dump_peedi',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='dump PEEDI'),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='dump_renesas',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='raspeedi',
            name='ref_mm',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
