# Generated by Django 3.2.18 on 2023-04-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0003_toolstatus_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolstatus',
            name='type',
            field=models.TextField(blank=True, max_length=50, verbose_name='Type'),
        ),
    ]
