# Generated by Django 3.2.18 on 2023-04-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0004_toolstatus_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="nom de l'AET")),
                ('path', models.CharField(max_length=500, unique=True, verbose_name='chemin du fichier')),
                ('filename', models.CharField(max_length=100, verbose_name='nom du fichier')),
                ('content', models.TextField(verbose_name='contenu du fichier')),
            ],
        ),
    ]
