# Generated by Django 3.2.19 on 2023-05-31 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0005_auto_20230526_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aet',
            old_name='raspi_ip',
            new_name='raspi_url',
        ),
    ]
