# Generated by Django 3.2.18 on 2023-04-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0005_aet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aet',
            name='content',
        ),
        migrations.RemoveField(
            model_name='aet',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='aet',
            name='path',
        ),
        migrations.AddField(
            model_name='aet',
            name='mbed_list',
            field=models.TextField(blank=True, max_length=500, verbose_name="Liste mbed de l'AET"),
        ),
        migrations.AddField(
            model_name='aet',
            name='raspi_ip',
            field=models.CharField(blank=True, max_length=500, verbose_name='Addresse ip raspi'),
        ),
        migrations.AlterField(
            model_name='aet',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom de l'AET"),
        ),
    ]
