# Generated by Django 3.2.18 on 2023-04-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0006_auto_20230424_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='MbedSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du soft mbed')),
                ('version', models.CharField(blank=True, max_length=500, verbose_name='Version du soft')),
                ('path', models.CharField(max_length=500, unique=True, verbose_name='chemin du fichier')),
                ('filename', models.CharField(max_length=100, verbose_name='nom du fichier')),
                ('content', models.TextField(verbose_name='contenu du fichier')),
            ],
        ),
        migrations.AlterModelOptions(
            name='aet',
            options={'ordering': ['name'], 'verbose_name': 'Statut AET'},
        ),
        migrations.AlterField(
            model_name='aet',
            name='raspi_ip',
            field=models.CharField(blank=True, max_length=500, verbose_name='Addresse IP raspi'),
        ),
    ]
