# Generated by Django 3.2.19 on 2023-06-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0006_rename_raspi_ip_aet_raspi_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aet',
            name='raspi_url',
            field=models.CharField(max_length=500, verbose_name='URL Raspi'),
        ),
    ]
