# Generated by Django 3.2.24 on 2024-02-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0007_alter_aet_raspi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolstatus',
            name='firmware',
            field=models.CharField(blank=True, max_length=20, verbose_name='Firmware'),
        ),
        migrations.AddField(
            model_name='toolstatus',
            name='last_boot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier démarrage'),
        ),
    ]
