# Generated by Django 3.2.18 on 2023-05-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0007_auto_20230425_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbedsoftware',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
    ]
