# Generated by Django 3.2.18 on 2023-05-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0008_mbedsoftware_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbedsoftware',
            name='content',
        ),
        migrations.RemoveField(
            model_name='mbedsoftware',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='mbedsoftware',
            name='path',
        ),
        migrations.AddField(
            model_name='mbedsoftware',
            name='file',
            field=models.FileField(default='null', upload_to='firmware', verbose_name='Fichier'),
        ),
    ]
