# Generated by Django 3.2.24 on 2024-03-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0008_auto_20240215_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolstatus',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hostname'),
        ),
        migrations.AddField(
            model_name='toolstatus',
            name='hw_revision',
            field=models.CharField(blank=True, max_length=500, verbose_name='Hardware revision'),
        ),
        migrations.AddField(
            model_name='toolstatus',
            name='ip_addr',
            field=models.CharField(blank=True, max_length=50, verbose_name='ip address'),
        ),
        migrations.AddField(
            model_name='toolstatus',
            name='mac_addr',
            field=models.CharField(blank=True, max_length=20, verbose_name='mac address'),
        ),
    ]
