# Generated by Django 3.2.18 on 2023-05-23 07:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0009_auto_20230522_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbedsoftware',
            name='file_url',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Lien du fichier'),
        ),
        migrations.AlterField(
            model_name='mbedsoftware',
            name='file',
            field=models.FileField(default='null', upload_to=django.core.files.storage.FileSystemStorage(), verbose_name='Fichier'),
        ),
    ]
