# Generated by Django 3.2.18 on 2023-05-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0010_auto_20230523_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbedsoftware',
            name='file_url',
        ),
        migrations.AlterField(
            model_name='mbedsoftware',
            name='file',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Lien du fichier'),
        ),
    ]
