# Generated by Django 3.2.18 on 2023-05-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0011_auto_20230523_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbedsoftware',
            name='file',
            field=models.CharField(default='null', max_length=100, unique=True, verbose_name='Lien du fichier'),
        ),
    ]
