# Generated by Django 3.2.25 on 2024-09-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('prog', '0012_toolstatus_mbed_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='AETLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xelon', models.CharField(max_length=10, verbose_name='numéro Xelon')),
                ('comp_ref', models.CharField(max_length=10, verbose_name='réf. comp. matériel')),
                ('manu_ref', models.CharField(max_length=100, verbose_name='réf. fabriquant')),
                ('aet_name', models.CharField(max_length=100, verbose_name="nom de l'AET")),
                ('prod_name', models.CharField(max_length=100, verbose_name='nom du produit')),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
            options={
                'verbose_name': 'Log AET',
                'ordering': ['xelon'],
            },
        ),
        migrations.CreateModel(
            name='AETMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_name', models.CharField(max_length=100, verbose_name='nom mesure')),
                ('measured_value', models.CharField(max_length=100, verbose_name='valeur mesurée')),
                ('min_value', models.CharField(max_length=100, verbose_name='valeur min.')),
                ('max_value', models.CharField(max_length=100, verbose_name='valeur max.')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Mesures AET',
            },
        ),
    ]
