# Generated by Django 3.2.18 on 2023-05-23 08:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0012_alter_mbedsoftware_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbedsoftware',
            name='file',
            field=models.FileField(default='null', storage=django.core.files.storage.FileSystemStorage(), upload_to='', verbose_name='Fichier'),
        ),
    ]
