# Generated by Django 3.2.25 on 2024-09-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0013_aetlog_aetmeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetmeasure',
            name='measure_name',
            field=models.CharField(max_length=1000, verbose_name='nom mesure'),
        ),
    ]
