# Generated by Django 4.2.16 on 2024-10-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0014_alter_aetmeasure_measure_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolstatus',
            name='fw_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Firmware version'),
        ),
    ]
