# Generated by Django 3.2.18 on 2023-05-23 09:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0014_alter_mbedsoftware_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbedsoftware',
            name='file',
        ),
        migrations.AddField(
            model_name='mbedsoftware',
            name='filepath',
            field=models.FileField(default='null', upload_to=django.core.files.storage.FileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='mbedsoftware',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
    ]
