# Generated by Django 3.2.18 on 2023-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0015_auto_20230523_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbedsoftware',
            name='version',
            field=models.CharField(max_length=500, verbose_name='Version du soft'),
        ),
    ]
