# Generated by Django 3.2.16 on 2023-02-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0042_alter_firmware_ecu_type'),
        ('prog', '0015_auto_20220404_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programing',
            name='multimedia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prog', to='psa.multimedia'),
        ),
    ]
