# Generated by Django 3.2.18 on 2023-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0016_alter_mbedsoftware_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='MbedFirmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du soft mbed')),
                ('version', models.CharField(max_length=500, verbose_name='Version du soft')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('filepath', models.FileField(upload_to='firmware/')),
            ],
        ),
        migrations.DeleteModel(
            name='MbedSoftware',
        ),
    ]
