# Generated by Django 3.2.18 on 2023-05-24 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0017_auto_20230524_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbedfirmware',
            name='version',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{2}.?[0-9]{2}$')], verbose_name='Version du soft'),
        ),
    ]
