# Generated by Django 3.2.18 on 2023-05-24 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0018_alter_mbedfirmware_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbedfirmware',
            name='version',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{1,2}.[0-9]{2}$', 'Please respect version format (ex : 1.23)')], verbose_name='Version du soft'),
        ),
    ]
